// resources/js/pages/Dashboard.vue
<template>
  <div>
    <div class="d-flex justify-space-between align-center mb-4 flex-wrap ga-2">
      <h5 class="text-h5 font-weight-bold">Дашборд партнёра</h5>
      <MonthPicker v-model="period" @update:model-value="loadData" />
    </div>

    <!-- Status Info Alert -->
    <v-alert v-if="data.statusInfo && data.statusInfo.daysRemaining != null" :type="data.statusInfo.daysRemaining <= 30 ? 'warning' : 'info'"
      variant="tonal" class="mb-4" closable>
      <div class="d-flex justify-space-between align-center flex-wrap ga-2">
        <div>
          <div class="font-weight-bold">Активационный период</div>
          <div class="text-body-2">
            Осталось <strong>{{ data.statusInfo.daysRemaining }}</strong> дней.
            Требуется набрать <strong>{{ fmt(data.statusInfo.requiredPoints) }}</strong> баллов.
            Текущий прогресс: <strong>{{ fmt(data.statusInfo.currentPoints) }}</strong> баллов.
          </div>
        </div>
      </div>
      <v-progress-linear :model-value="statusProgress" height="8" rounded
        :color="data.statusInfo.daysRemaining <= 30 ? 'warning' : 'primary'" class="mt-2" />
    </v-alert>

    <!-- Status + Qualification -->
    <v-card class="mb-4 pa-4">
      <div class="d-flex justify-space-between align-center mb-3 flex-wrap ga-2">
        <div>
          <div class="text-body-2 text-medium-emphasis">Статус</div>
          <div class="d-flex align-center ga-2">
            <span class="text-h6">{{ data.consultant.statusName }}</span>
            <v-chip v-if="data.consultant.activityName" size="small"
              :color="data.consultant.active ? 'success' : 'grey'">
              {{ data.consultant.activityName }}
            </v-chip>
          </div>
        </div>
        <v-btn variant="outlined" color="secondary" @click="showLevels = true">Условия перехода</v-btn>
      </div>
      <v-row>
        <v-col cols="12" md="4">
          <div class="text-body-2 text-medium-emphasis">Закрытая квалификация</div>
          <div class="d-flex align-center ga-2">
            <v-chip size="small" color="secondary">{{ data.qualification.nominalLevel?.level ?? '—' }}</v-chip>
            <span class="font-weight-medium">{{ data.qualification.nominalLevel?.title ?? '—' }}</span>
          </div>
        </v-col>
        <v-col cols="12" md="4">
          <div class="text-body-2 text-medium-emphasis">Комиссия</div>
          <v-chip size="small" color="primary">{{ data.qualification.nominalLevel?.percent ?? 0 }}%</v-chip>
        </v-col>
        <v-col cols="12" md="4">
          <div class="text-body-2 text-medium-emphasis">НГП</div>
          <v-progress-linear :model-value="nqpProgress" height="10" rounded color="primary" class="mb-1" />
          <div class="text-body-2">{{ fmt(data.volumes.groupVolumeCumulative) }} / {{ fmt(data.qualification.nextLevel?.groupVolumeCumulative ?? 0) }}</div>
        </v-col>
      </v-row>
    </v-card>

    <!-- Volumes -->
    <h6 class="text-h6 mb-3">Показатели</h6>
    <v-row class="mb-4">
      <v-col v-for="card in volumeCards" :key="card.title" cols="12" md="4">
        <v-card class="pa-4">
          <div class="d-flex justify-space-between">
            <div>
              <div class="text-body-2 text-medium-emphasis">{{ card.title }}</div>
              <div class="text-h4 font-weight-bold my-1">{{ fmt(card.value) }}</div>
              <div class="d-flex align-center ga-1">
                <v-icon :color="card.changeType === 'up' ? 'success' : 'error'" size="16">
                  {{ card.changeType === 'up' ? 'mdi-trending-up' : 'mdi-trending-down' }}
                </v-icon>
                <span class="text-caption" :class="card.changeType === 'up' ? 'text-success' : 'text-error'">
                  {{ card.change }} к прошлому месяцу
                </span>
              </div>
            </div>
            <v-avatar :color="card.color" size="48" variant="tonal">
              <v-icon>{{ card.icon }}</v-icon>
            </v-avatar>
          </div>
        </v-card>
      </v-col>
    </v-row>

    <!-- Breakaway -->
    <v-card v-if="data.breakaway" class="mb-4 pa-4" color="amber-lighten-5" variant="tonal">
      <div class="d-flex align-center ga-2 mb-2">
        <v-icon color="amber-darken-2">mdi-alert-decagram</v-icon>
        <span class="text-h6 font-weight-bold text-amber-darken-3">Отрыв зафиксирован</span>
      </div>
      <v-row>
        <v-col cols="12" sm="6" md="3">
          <div class="text-body-2 text-medium-emphasis">Ветка</div>
          <div class="font-weight-medium">{{ data.breakaway.branchWithGapName || '—' }}</div>
        </v-col>
        <v-col cols="12" sm="6" md="3">
          <div class="text-body-2 text-medium-emphasis">ГП ветки</div>
          <div class="font-weight-medium">{{ fmt(data.breakaway.branchWithGapGroupVolume) }}</div>
        </v-col>
        <v-col cols="12" sm="6" md="3">
          <div class="text-body-2 text-medium-emphasis">Разница (баллы)</div>
          <div class="font-weight-medium">{{ fmt(data.breakaway.gapValue) }}</div>
        </v-col>
        <v-col cols="12" sm="6" md="3">
          <div class="text-body-2 text-medium-emphasis">Разница (%)</div>
          <div class="font-weight-medium">{{ data.breakaway.gapValuePercentage ?? 0 }}%</div>
        </v-col>
      </v-row>
    </v-card>

    <!-- Partners block -->
    <h6 class="text-h6 mb-3">Партнёры</h6>
    <v-row class="mb-4">
      <v-col v-for="card in partnerCards" :key="card.label" cols="12" sm="6" md="3">
        <router-link to="/structure" style="text-decoration: none; color: inherit">
          <v-card class="pa-4 text-center" hover>
            <div class="text-body-2 text-medium-emphasis">{{ card.label }}</div>
            <div class="text-h3 font-weight-bold" :class="`text-${card.color}`">{{ card.value }}</div>
            <div v-if="card.diff != null" class="d-flex align-center justify-center ga-1 mt-1">
              <v-icon :color="card.diff >= 0 ? 'success' : 'error'" size="14">
                {{ card.diff >= 0 ? 'mdi-trending-up' : 'mdi-trending-down' }}
              </v-icon>
              <span class="text-caption" :class="card.diff >= 0 ? 'text-success' : 'text-error'">
                {{ card.diff >= 0 ? '+' : '' }}{{ card.diff }} к прошлому периоду
              </span>
            </div>
          </v-card>
        </router-link>
      </v-col>
    </v-row>

    <!-- Clients block -->
    <h6 class="text-h6 mb-3">Клиенты</h6>
    <v-row class="mb-4">
      <v-col cols="12" sm="6">
        <router-link to="/clients" style="text-decoration: none; color: inherit">
          <v-card class="pa-4 text-center" hover>
            <v-icon size="32" color="primary" class="mb-2">mdi-account-multiple</v-icon>
            <div class="text-body-2 text-medium-emphasis">Мои клиенты</div>
            <div class="text-h3 font-weight-bold text-primary">{{ data.team.myClients }}</div>
          </v-card>
        </router-link>
      </v-col>
      <v-col cols="12" sm="6">
        <router-link to="/clients" style="text-decoration: none; color: inherit">
          <v-card class="pa-4 text-center" hover>
            <v-icon size="32" color="secondary" class="mb-2">mdi-account-group</v-icon>
            <div class="text-body-2 text-medium-emphasis">Клиенты команды</div>
            <div class="text-h3 font-weight-bold text-secondary">{{ data.team.teamClients }}</div>
          </v-card>
        </router-link>
      </v-col>
    </v-row>

    <!-- Qualification transition table -->
    <h6 class="text-h6 mb-3">Таблица квалификаций</h6>
    <v-card class="mb-4">
      <v-table density="compact" hover>
        <thead>
          <tr>
            <th>Уровень</th>
            <th>Квалификация</th>
            <th class="text-right">НГП</th>
            <th class="text-right">ГП</th>
            <th class="text-right">ЛП</th>
            <th class="text-right">Кол-во партнёров</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="lv in levels" :key="lv.id"
            :class="lv.level === data.qualification.nominalLevel?.level ? 'bg-green-lighten-5' : ''">
            <td>{{ lv.level }}</td>
            <td class="font-weight-medium">
              {{ lv.title }}
              <v-chip v-if="lv.level === data.qualification.nominalLevel?.level" size="x-small" color="success" class="ml-1">Текущий</v-chip>
            </td>
            <td class="text-right">{{ fmt(lv.groupVolumeCumulative) }}</td>
            <td class="text-right">{{ fmt(lv.groupVolume) }}</td>
            <td class="text-right">{{ fmt(lv.personalVolume ?? 0) }}</td>
            <td class="text-right">{{ lv.partnersCount ?? '—' }}</td>
          </tr>
        </tbody>
      </v-table>
    </v-card>

    <!-- Levels dialog (full conditions) -->
    <v-dialog v-model="showLevels" max-width="900">
      <v-card>
        <v-card-title>Условия перехода</v-card-title>
        <v-card-text>
          <v-table density="compact">
            <thead>
              <tr>
                <th>No.</th><th>Квалификация</th><th class="text-right">%</th>
                <th class="text-right">ЛП</th><th class="text-right">ГП</th>
                <th class="text-right">НГП</th><th class="text-right">Отрыв</th>
                <th class="text-right">Пул</th><th class="text-right">Доля DS</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="lv in levels" :key="lv.id" :class="lv.level === data.qualification.nominalLevel?.level ? 'bg-green-lighten-5' : ''">
                <td>{{ lv.level }}</td>
                <td class="font-weight-medium">
                  {{ lv.title }}
                  <v-chip v-if="lv.level === data.qualification.nominalLevel?.level" size="x-small" color="success" class="ml-1">Текущий</v-chip>
                </td>
                <td class="text-right">{{ lv.percent }}%</td>
                <td class="text-right">{{ fmt(lv.personalVolume ?? 0) }}</td>
                <td class="text-right">{{ fmt(lv.groupVolume) }}</td>
                <td class="text-right">{{ fmt(lv.groupVolumeCumulative) }}</td>
                <td class="text-right">{{ fmt(lv.breakaway ?? 0) }}</td>
                <td class="text-right">{{ lv.pool }}%</td>
                <td class="text-right">{{ lv.dsShare ?? '—' }}</td>
              </tr>
            </tbody>
          </v-table>
        </v-card-text>
        <v-card-actions><v-btn @click="showLevels = false">Закрыть</v-btn></v-card-actions>
      </v-card>
    </v-dialog>

    <v-overlay v-model="loading" class="align-center justify-center" persistent>
      <v-progress-circular indeterminate size="64" />
    </v-overlay>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import api from '../api';
import MonthPicker from '../components/MonthPicker.vue';

const loading = ref(true);
const period = ref(new Date().toISOString().slice(0, 7));
const showLevels = ref(false);
const levels = ref([]);

const empty = {
  consultant: { id: 0, personName: '—', statusName: 'Партнёр', participantCode: null, active: false, ambassadorProducts: null, activityName: null },
  qualification: { nominalLevel: null, nextLevel: null },
  volumes: { personalVolume: 0, groupVolume: 0, groupVolumeCumulative: 0, prevPersonalVolume: 0, prevGroupVolume: 0, prevGroupVolumeCumulative: 0 },
  team: { myClients: 0, teamClients: 0 },
  statusInfo: null,
  partners: { total: 0, registered: 0, active: 0, terminated: 0 },
  prevPartners: { total: 0, registered: 0, active: 0, terminated: 0 },
};
const data = ref({ ...empty });

const fmt = (n) => Number(n || 0).toLocaleString('ru-RU', { minimumFractionDigits: 0 });

function pct(cur, prev) {
  if (!prev && !cur) return { value: '0%', type: 'neutral' };
  if (!prev) return { value: '+100%', type: 'up' };
  const p = ((cur - prev) / prev) * 100;
  return { value: `${p >= 0 ? '+' : ''}${p.toFixed(1)}%`, type: p >= 0 ? 'up' : 'down' };
}

const statusProgress = computed(() => {
  const si = data.value.statusInfo;
  if (!si || !si.requiredPoints) return 0;
  return Math.min((si.currentPoints / si.requiredPoints) * 100, 100);
});

const volumeCards = computed(() => {
  const v = data.value.volumes;
  const lp = pct(v.personalVolume, v.prevPersonalVolume);
  const gp = pct(v.groupVolume, v.prevGroupVolume);
  const ngp = pct(v.groupVolumeCumulative, v.prevGroupVolumeCumulative);
  return [
    { title: 'Личные продажи (ЛП)', value: v.personalVolume, change: lp.value, changeType: lp.type, icon: 'mdi-bank', color: 'green' },
    { title: 'Групповые продажи (ГП)', value: v.groupVolume, change: gp.value, changeType: gp.type, icon: 'mdi-account-group', color: 'blue' },
    { title: 'Накопленные ГП (НГП)', value: v.groupVolumeCumulative, change: ngp.value, changeType: ngp.type, icon: 'mdi-trending-up', color: 'orange' },
  ];
});

const partnerCards = computed(() => {
  const p = data.value.partners || {};
  const pp = data.value.prevPartners || {};
  return [
    { label: 'Всего партнёров', value: p.total ?? 0, color: 'primary', diff: (p.total ?? 0) - (pp.total ?? 0) },
    { label: 'Зарегистрировано', value: p.registered ?? 0, color: 'info', diff: (p.registered ?? 0) - (pp.registered ?? 0) },
    { label: 'Активных', value: p.active ?? 0, color: 'success', diff: (p.active ?? 0) - (pp.active ?? 0) },
    { label: 'Терминированных', value: p.terminated ?? 0, color: 'error', diff: (p.terminated ?? 0) - (pp.terminated ?? 0) },
  ];
});

const nqpProgress = computed(() => {
  const target = data.value.qualification.nextLevel?.groupVolumeCumulative || 1;
  return Math.min((data.value.volumes.groupVolumeCumulative / target) * 100, 100);
});

async function loadData() {
  loading.value = true;
  try {
    const { data: d } = await api.get('/dashboard', { params: { month: period.value } });
    data.value = { ...empty, ...d };
  } catch {
    data.value = { ...empty };
  }
  loading.value = false;
}

onMounted(async () => {
  loadData();
  try {
    const { data: d } = await api.get('/status-levels');
    levels.value = d;
  } catch {}
});
</script>

// frontend/src/pages/Dashboard/index.tsx
import React, { useState, useEffect } from 'react';
import {
  Box, Grid, Card, CardContent, Typography, LinearProgress, Chip, Button,
  CircularProgress, Dialog, DialogTitle, DialogContent, DialogActions,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper,
  TextField, Alert,
} from '@mui/material';
import {
  TrendingUp, TrendingDown, People, AccountBalance, Remove,
  Groups, PersonAdd, PersonOff, Block, Timer,
} from '@mui/icons-material';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { dashboardApi, DashboardData, StatusLevel } from '../../api/dashboard';
import { t } from '../../i18n';

const fmt = (n: number) => n.toLocaleString('ru-RU', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const fmtInt = (n: number) => n.toLocaleString('ru-RU');

const changePercent = (current: number, prev: number): { value: string; type: 'up' | 'down' | 'neutral' } => {
  if (prev === 0 && current === 0) return { value: '0%', type: 'neutral' };
  if (prev === 0) return { value: '+100%', type: 'up' };
  const pct = ((current - prev) / prev) * 100;
  return {
    value: `${pct >= 0 ? '+' : ''}${pct.toFixed(1)}%`,
    type: pct >= 0 ? 'up' : 'down',
  };
};

const changeDiff = (current: number, prev: number): { value: string; type: 'up' | 'down' | 'neutral' } => {
  const diff = current - prev;
  if (diff === 0) return { value: '0', type: 'neutral' };
  return { value: `${diff > 0 ? '+' : ''}${diff}`, type: diff > 0 ? 'up' : 'down' };
};

interface StatCardProps {
  title: string;
  value: string;
  change?: { value: string; type: 'up' | 'down' | 'neutral' };
  icon: React.ReactNode;
  color: string;
  onClick?: () => void;
}

const StatCard: React.FC<StatCardProps> = ({ title, value, change, icon, color, onClick }) => (
  <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
    <Card
      sx={{ cursor: onClick ? 'pointer' : 'default', '&:hover': onClick ? { boxShadow: 6 } : {} }}
      onClick={onClick}
    >
      <CardContent sx={{ p: 3 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <Box>
            <Typography variant="body2" color="text.secondary" gutterBottom>{title}</Typography>
            <Typography variant="h4" sx={{ fontWeight: 700, mb: 1 }}>{value}</Typography>
            {change && (
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                {change.type === 'up' ? <TrendingUp sx={{ fontSize: 16, color: 'success.main' }} /> :
                 change.type === 'down' ? <TrendingDown sx={{ fontSize: 16, color: 'error.main' }} /> :
                 <Remove sx={{ fontSize: 16, color: 'text.secondary' }} />}
                <Typography variant="caption" sx={{ color: change.type === 'up' ? 'success.main' : change.type === 'down' ? 'error.main' : 'text.secondary' }}>
                  {change.value} {t('dashboard.toLastMonth')}
                </Typography>
              </Box>
            )}
          </Box>
          <Box sx={{ bgcolor: `${color}15`, borderRadius: 2, p: 1, display: 'flex' }}>
            {React.cloneElement(icon as React.ReactElement<any>, { sx: { color, fontSize: 28 } })}
          </Box>
        </Box>
      </CardContent>
    </Card>
  </motion.div>
);

const Dashboard: React.FC = () => {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState(new Date().toISOString().slice(0, 7));
  const [levelsOpen, setLevelsOpen] = useState(false);
  const [levels, setLevels] = useState<StatusLevel[]>([]);
  const navigate = useNavigate();

  const emptyData: DashboardData = {
    consultant: { id: 0, personName: '—', participantCode: null, active: false, statusName: 'Резидент', ambassadorProducts: null },
    statusInfo: { activityId: 4, activityName: 'Зарегистрирован', hasAccess: true, canInvite: false, terminationCount: 0, maxTerminations: 3 },
    qualification: { nominalLevel: null, nextLevel: null },
    volumes: { personalVolume: 0, groupVolume: 0, groupVolumeCumulative: 0, prevPersonalVolume: 0, prevGroupVolume: 0, prevGroupVolumeCumulative: 0 },
    team: { myClients: 0, teamClients: 0, firstLineResidents: 0, totalResidents: 0, firstLineConsultants: 0, totalConsultants: 0, capitalUsd: 0 },
    partners: { total: 0, registered: 0, active: 0, inactive: 0, terminated: 0, excluded: 0 },
    prevPartners: { total: 0, registered: 0, active: 0, inactive: 0, terminated: 0, excluded: 0 },
    period: period,
  };

  useEffect(() => {
    setLoading(true);
    dashboardApi.get(period)
      .then((res) => setData(res.data))
      .catch(() => setData(emptyData))
      .finally(() => setLoading(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [period]);

  const openLevels = async () => {
    if (levels.length === 0) {
      const res = await dashboardApi.getStatusLevels();
      setLevels(res.data);
    }
    setLevelsOpen(true);
  };

  if (loading) {
    return <Box sx={{ display: 'flex', justifyContent: 'center', py: 10 }}><CircularProgress /></Box>;
  }

  if (!data) {
    return <Typography color="error">{t('common.loading')}...</Typography>;
  }

  const { consultant, statusInfo, qualification, volumes, team, partners, prevPartners } = data;
  const level = qualification.nominalLevel;
  const nextLvl = qualification.nextLevel;

  const nqpProgress = nextLvl && nextLvl.groupVolumeCumulative > 0
    ? Math.min((volumes.groupVolumeCumulative / nextLvl.groupVolumeCumulative) * 100, 100)
    : 0;

  // Activation progress for status bar
  const activationProgress = statusInfo.requiredPoints && statusInfo.requiredPoints > 0
    ? Math.min(((statusInfo.currentPoints ?? 0) / statusInfo.requiredPoints) * 100, 100)
    : 0;

  return (
    <Box>
      {/* Period selector */}
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3, flexWrap: 'wrap', gap: 2 }}>
        <Typography variant="h5" sx={{ fontWeight: 600 }}>{t('dashboard.title')}</Typography>
        <TextField
          type="month"
          value={period}
          onChange={(e) => setPeriod(e.target.value)}
          size="small"
          sx={{ width: 200 }}
        />
      </Box>

      {/* Status alert with countdown */}
      {statusInfo.daysRemaining !== undefined && statusInfo.daysRemaining <= 90 && (
        <Alert
          severity={statusInfo.daysRemaining <= 30 ? 'warning' : 'info'}
          icon={<Timer />}
          sx={{ mb: 3 }}
        >
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, flexWrap: 'wrap' }}>
            <Box>
              <Typography variant="body2" sx={{ fontWeight: 600 }}>
                {statusInfo.activityName} — {statusInfo.daysRemaining} {t('dashboard.daysRemaining')}
              </Typography>
              <Typography variant="caption" color="text.secondary">
                {t('dashboard.requiredPoints')}: {statusInfo.requiredPoints}
                {' | '}
                Набрано: {fmtInt(statusInfo.currentPoints ?? 0)}
              </Typography>
            </Box>
            <LinearProgress
              variant="determinate"
              value={activationProgress}
              sx={{ flexGrow: 1, minWidth: 120, height: 8, borderRadius: 4 }}
              color={statusInfo.daysRemaining <= 30 ? 'warning' : 'primary'}
            />
          </Box>
        </Alert>
      )}

      {/* Qualification header */}
      <Card sx={{ mb: 3 }}>
        <CardContent sx={{ p: 3 }}>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2, flexWrap: 'wrap', gap: 1 }}>
            <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
              <Box>
                <Typography variant="body2" color="text.secondary">{t('dashboard.status')}</Typography>
                <Typography variant="h6">{consultant.statusName}</Typography>
              </Box>
              <Chip
                label={statusInfo.activityName}
                size="small"
                color={
                  statusInfo.activityId === 1 ? 'success' :
                  statusInfo.activityId === 4 ? 'info' :
                  statusInfo.activityId === 3 ? 'warning' :
                  statusInfo.activityId === 5 ? 'error' : 'default'
                }
              />
            </Box>
            <Button variant="outlined" color="secondary" onClick={openLevels}>
              {t('dashboard.transitionConditions')}
            </Button>
          </Box>

          <Grid container spacing={3}>
            <Grid size={{ xs: 12, md: 4 }}>
              <Typography variant="body2" color="text.secondary" gutterBottom>
                {t('dashboard.qualificationClosed')}
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                <Chip label={level?.level ?? '—'} size="small" color="secondary" />
                <Typography variant="body2" sx={{ fontWeight: 600 }}>{level?.title ?? '—'}</Typography>
              </Box>
            </Grid>
            <Grid size={{ xs: 12, md: 4 }}>
              <Typography variant="body2" color="text.secondary" gutterBottom>
                {t('dashboard.commissionLevel')}
              </Typography>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'center' }}>
                <Chip label={`${level?.percent ?? 0}%`} size="small" color="primary" />
                <Typography variant="body2" sx={{ fontWeight: 600 }}>{t('dashboard.commission')} {level?.percent ?? 0}%</Typography>
              </Box>
            </Grid>
            <Grid size={{ xs: 12, md: 4 }}>
              <Typography variant="body2" color="text.secondary" gutterBottom>
                {t('dashboard.cumulativeGroupVolume')}
              </Typography>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                <LinearProgress
                  variant="determinate"
                  value={nqpProgress}
                  sx={{ flexGrow: 1, height: 8, borderRadius: 4 }}
                />
                <Typography variant="body2">
                  {fmtInt(volumes.groupVolumeCumulative)} / {fmtInt(nextLvl?.groupVolumeCumulative ?? 0)}
                </Typography>
              </Box>
            </Grid>
          </Grid>

          {consultant.ambassadorProducts && (
            <Box sx={{ mt: 2 }}>
              <Typography variant="body2" color="text.secondary">Амбассадор продуктов</Typography>
              <Box sx={{ display: 'flex', gap: 0.5, mt: 0.5, flexWrap: 'wrap' }}>
                {consultant.ambassadorProducts.split(',').map((p) => (
                  <Chip key={p} label={p.trim()} size="small" variant="outlined" />
                ))}
              </Box>
            </Box>
          )}
        </CardContent>
      </Card>

      {/* Volume indicators */}
      <Typography variant="h6" sx={{ mb: 2 }}>{t('dashboard.indicators')}</Typography>
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{ xs: 12, md: 4 }}>
          <StatCard
            title={t('dashboard.personalSales')}
            value={fmt(volumes.personalVolume)}
            change={changePercent(volumes.personalVolume, volumes.prevPersonalVolume)}
            icon={<AccountBalance />}
            color="#4CAF50"
          />
        </Grid>
        <Grid size={{ xs: 12, md: 4 }}>
          <StatCard
            title={t('dashboard.groupSales')}
            value={fmt(volumes.groupVolume)}
            change={changePercent(volumes.groupVolume, volumes.prevGroupVolume)}
            icon={<People />}
            color="#2196F3"
          />
        </Grid>
        <Grid size={{ xs: 12, md: 4 }}>
          <StatCard
            title={t('dashboard.cumulativeGroupSales')}
            value={fmt(volumes.groupVolumeCumulative)}
            change={changePercent(volumes.groupVolumeCumulative, volumes.prevGroupVolumeCumulative)}
            icon={<TrendingUp />}
            color="#FF9800"
          />
        </Grid>
      </Grid>

      {/* Partner counts by status */}
      <Typography variant="h6" sx={{ mb: 2 }}>{t('dashboard.partners')}</Typography>
      <Grid container spacing={3} sx={{ mb: 3 }}>
        <Grid size={{ xs: 6, md: 3 }}>
          <StatCard
            title={t('dashboard.partnersTotal')}
            value={fmtInt(partners.total)}
            change={changeDiff(partners.total, prevPartners.total)}
            icon={<Groups />}
            color="#673AB7"
            onClick={() => navigate('/structure')}
          />
        </Grid>
        <Grid size={{ xs: 6, md: 3 }}>
          <StatCard
            title={t('dashboard.partnersRegistered')}
            value={fmtInt(partners.registered)}
            change={changeDiff(partners.registered, prevPartners.registered)}
            icon={<PersonAdd />}
            color="#2196F3"
            onClick={() => navigate('/structure')}
          />
        </Grid>
        <Grid size={{ xs: 6, md: 3 }}>
          <StatCard
            title={t('dashboard.partnersActive')}
            value={fmtInt(partners.active)}
            change={changeDiff(partners.active, prevPartners.active)}
            icon={<People />}
            color="#4CAF50"
            onClick={() => navigate('/structure')}
          />
        </Grid>
        <Grid size={{ xs: 6, md: 3 }}>
          <StatCard
            title={t('dashboard.partnersTerminated')}
            value={fmtInt(partners.terminated)}
            change={changeDiff(partners.terminated, prevPartners.terminated)}
            icon={<PersonOff />}
            color="#FF9800"
            onClick={() => navigate('/structure')}
          />
        </Grid>
      </Grid>

      {/* Team stats */}
      <Grid container spacing={3}>
        <Grid size={{ xs: 6, md: 3 }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.3 }}>
            <Card sx={{ cursor: 'pointer', '&:hover': { boxShadow: 6 } }} onClick={() => navigate('/clients')}>
              <CardContent sx={{ textAlign: 'center', p: 3 }}>
                <Typography variant="body2" color="text.secondary" gutterBottom>{t('nav.clientList')}</Typography>
                <Typography variant="h3" sx={{ fontWeight: 700, color: 'primary.main' }}>{fmtInt(team.myClients)}</Typography>
              </CardContent>
            </Card>
          </motion.div>
        </Grid>
        <Grid size={{ xs: 6, md: 3 }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.35 }}>
            <Card sx={{ cursor: 'pointer', '&:hover': { boxShadow: 6 } }} onClick={() => navigate('/clients')}>
              <CardContent sx={{ textAlign: 'center', p: 3 }}>
                <Typography variant="body2" color="text.secondary" gutterBottom>{t('dashboard.teamClients')}</Typography>
                <Typography variant="h3" sx={{ fontWeight: 700, color: 'primary.main' }}>{fmtInt(team.teamClients)}</Typography>
              </CardContent>
            </Card>
          </motion.div>
        </Grid>
        <Grid size={{ xs: 12, md: 6 }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.4 }}>
            <Card>
              <CardContent sx={{ textAlign: 'center', p: 3 }}>
                <Typography variant="body2" color="text.secondary" gutterBottom>{t('dashboard.capitalUnderManagement')}</Typography>
                <Typography variant="h3" sx={{ fontWeight: 700 }}>{fmtInt(team.capitalUsd)} USD</Typography>
              </CardContent>
            </Card>
          </motion.div>
        </Grid>
      </Grid>

      {/* Status levels dialog */}
      <Dialog open={levelsOpen} onClose={() => setLevelsOpen(false)} maxWidth="lg" fullWidth>
        <DialogTitle>{t('dashboard.transitionConditions')}</DialogTitle>
        <DialogContent>
          <TableContainer component={Paper} variant="outlined">
            <Table size="small">
              <TableHead>
                <TableRow sx={{ bgcolor: '#f5f5f5' }}>
                  <TableCell>{t('dashboard.qualLevel')}</TableCell>
                  <TableCell>{t('dashboard.qualTitle')}</TableCell>
                  <TableCell align="right">{t('dashboard.qualPercent')}</TableCell>
                  <TableCell align="right">{t('dashboard.qualNGP')}</TableCell>
                  <TableCell align="right">{t('dashboard.qualOP')}</TableCell>
                  <TableCell align="right">{t('dashboard.qualGapGP')}</TableCell>
                  <TableCell align="right">{t('dashboard.qualPool')}</TableCell>
                  <TableCell align="right">{t('dashboard.qualDsShare')}</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {levels.map((lv) => (
                  <TableRow
                    key={lv.id}
                    sx={{
                      bgcolor: level && lv.level === level.level ? 'rgba(76,175,80,0.1)' : 'inherit',
                    }}
                  >
                    <TableCell>{lv.level}</TableCell>
                    <TableCell sx={{ fontWeight: level && lv.level === level.level ? 700 : 400 }}>
                      {lv.title}
                      {level && lv.level === level.level && (
                        <Chip label="Текущий" size="small" color="success" sx={{ ml: 1 }} />
                      )}
                    </TableCell>
                    <TableCell align="right">{lv.percent}%</TableCell>
                    <TableCell align="right">{fmtInt(lv.groupVolumeCumulative)}</TableCell>
                    <TableCell align="right">{lv.personalVolume > 0 ? fmtInt(lv.personalVolume) : '—'}</TableCell>
                    <TableCell align="right">{lv.otrif > 0 ? `${lv.otrif}%` : '—'}</TableCell>
                    <TableCell align="right">{lv.pool > 0 ? `${lv.pool}%` : '—'}</TableCell>
                    <TableCell align="right">{lv.dsShare > 0 ? `${lv.dsShare}%` : '—'}</TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setLevelsOpen(false)}>{t('common.close')}</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default Dashboard;
