// resources/js/pages/Profile.vue
<template>
  <div>
    <PageHeader title="Профиль" icon="mdi-account" />

    <v-tabs v-model="tab" color="primary" class="mb-4">
      <v-tab value="info">Информация о партнере</v-tab>
      <v-tab value="requisites">Реквизиты и документы для выплат</v-tab>
      <v-tab value="referral">Реферальные с��ылки</v-tab>
    </v-tabs>

    <v-tabs-window v-model="tab">
      <!-- Section 1: Partner Info -->
      <v-tabs-window-item value="info">
        <v-card class="pa-4 mb-4">
          <div class="d-flex align-center ga-4 mb-4">
            <v-avatar color="primary" size="72">
              <v-img v-if="profile.user?.avatar" :src="profile.user.avatar" />
              <span v-else class="text-h5 text-white">{{ initials }}</span>
            </v-avatar>
            <div>
              <div class="text-h6">{{ profile.user?.lastName }} {{ profile.user?.firstName }} {{ profile.user?.patronymic }}</div>
              <div class="text-body-2 text-medium-emphasis">{{ profile.user?.email }}</div>
            </div>
          </div>

          <v-row dense>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.lastName" label="Фамилия" disabled prepend-inner-icon="mdi-lock" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.firstName" label="Имя" disabled prepend-inner-icon="mdi-lock" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.patronymic" label="Отчество" disabled prepend-inner-icon="mdi-lock" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.birthDate" label="Дата рождения" type="date" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-select v-model="form.gender" label="Пол" :items="genderOptions" clearable />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.country" label="Страна" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.city" label="Город" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.email" label="Email" type="email" prepend-inner-icon="mdi-email" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.phone" label="Телефон" prepend-inner-icon="mdi-phone" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="form.telegram" label="Telegram" prepend-inner-icon="mdi-send" />
            </v-col>
          </v-row>
          <v-btn color="primary" :loading="saving" @click="saveProfile" class="mt-2" prepend-icon="mdi-content-save">Сохранить</v-btn>
          <v-alert v-if="saveMsg" :type="saveMsgType" density="compact" class="mt-3" closable @click:close="saveMsg = ''">{{ saveMsg }}</v-alert>
        </v-card>

        <!-- Signed Documents -->
        <v-card v-if="profile.signedDocuments?.length" class="pa-4 mb-4">
          <div class="text-subtitle-1 font-weight-bold mb-2">Подписанные документы</div>
          <v-list density="compact">
            <v-list-item v-for="doc in profile.signedDocuments" :key="doc.id"
              :href="doc.url || undefined" :target="doc.url ? '_blank' : undefined"
              prepend-icon="mdi-file-check">
              <v-list-item-title>{{ doc.name }}</v-list-item-title>
              <v-list-item-subtitle>Подписано: {{ doc.signedAt }}</v-list-item-subtitle>
            </v-list-item>
          </v-list>
        </v-card>

        <!-- Password Change -->
        <v-card class="pa-4">
          <div class="text-subtitle-1 font-weight-bold mb-2">Смена пароля</div>
          <v-row dense>
            <v-col cols="12" sm="4">
              <v-text-field v-model="pwd.current_password" label="Текущий пароль" type="password" prepend-inner-icon="mdi-lock" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="pwd.password" label="Новый пароль" type="password" prepend-inner-icon="mdi-lock-reset" />
            </v-col>
            <v-col cols="12" sm="4">
              <v-text-field v-model="pwd.password_confirmation" label="Подтверждение" type="password" prepend-inner-icon="mdi-lock-check" />
            </v-col>
          </v-row>
          <v-btn color="primary" :loading="savingPwd" @click="changePassword" class="mt-2" prepend-icon="mdi-key">Сменить пароль</v-btn>
          <v-alert v-if="pwdMsg" :type="pwdMsgType" density="compact" class="mt-3" closable @click:close="pwdMsg = ''">{{ pwdMsg }}</v-alert>
        </v-card>
      </v-tabs-window-item>

      <!-- Section 2: Requisites and documents for payments -->
      <v-tabs-window-item value="requisites">
        <!-- Documents -->
        <v-card class="pa-4 mb-4">
          <div class="d-flex align-center ga-2 mb-3">
            <v-icon color="primary">mdi-file-document-multiple</v-icon>
            <div class="text-subtitle-1 font-weight-bold">Документы партнёра</div>
          </div>
          <v-row dense>
            <v-col v-for="slot in documentSlots" :key="slot.type" cols="12" sm="4">
              <v-card variant="outlined" class="pa-3">
                <div class="d-flex align-center ga-2 mb-2">
                  <span class="text-body-2 font-weight-medium">{{ slot.label }}</span>
                  <v-icon v-if="isDocUploaded(slot.type)" color="success" size="20">mdi-check-circle</v-icon>
                </div>
                <v-file-input
                  v-model="docFiles[slot.type]"
                  accept="image/*,.pdf"
                  density="compact"
                  variant="outlined"
                  :label="isDocUploaded(slot.type) ? 'Загружено' : 'Выберите файл'"
                  prepend-icon=""
                  prepend-inner-icon="mdi-paperclip"
                  hide-details
                />
                <v-btn
                  color="primary"
                  size="small"
                  variant="tonal"
                  class="mt-2"
                  :loading="docUploading[slot.type]"
                  :disabled="!docFiles[slot.type]"
                  prepend-icon="mdi-upload"
                  @click="uploadDocument(slot.type)"
                >
                  Загрузить
                </v-btn>
              </v-card>
            </v-col>
          </v-row>
          <v-alert v-if="docMsg" :type="docMsgType" density="compact" class="mt-3" closable @click:close="docMsg = ''">{{ docMsg }}</v-alert>
        </v-card>

        <!-- IP Requisites -->
        <v-card class="pa-4 mb-4">
          <div class="d-flex align-center ga-2 mb-3">
            <v-icon color="primary">mdi-domain</v-icon>
            <div class="text-subtitle-1 font-weight-bold">Реквизиты ИП</div>
            <v-chip v-if="profile.requisites?.verificationStatus" size="small"
              :color="verificationColor(profile.requisites.verificationStatus)">
              {{ verificationLabel(profile.requisites.verificationStatus) }}
            </v-chip>
          </div>
          <v-alert v-if="profile.requisites?.verificationStatus === 'verified'" type="warning" density="compact" class="mb-3" variant="tonal">
            <v-icon class="mr-1">mdi-alert</v-icon>
            Изменение реквизитов сбросит статус верификации
          </v-alert>
          <v-row dense>
            <v-col cols="12" sm="6">
              <v-text-field v-model="reqForm.individualEntrepreneur" label="Наименование ИП" />
            </v-col>
            <v-col cols="12" sm="3">
              <v-text-field v-model="reqForm.inn" label="ИНН" />
            </v-col>
            <v-col cols="12" sm="3">
              <v-text-field v-model="reqForm.ogrn" label="ОГРН/ОГРНИП" />
            </v-col>
            <v-col cols="12">
              <v-text-field v-model="reqForm.address" label="Юридический адрес" />
            </v-col>
            <v-col cols="12">
              <v-checkbox v-model="addressSameAsRegistration" label="Адрес регистрации совпадает с фактическим" density="compact" hide-details />
            </v-col>
            <v-col v-if="!addressSameAsRegistration" cols="12">
              <v-text-field v-model="reqForm.actualAddress" label="Фактический адрес" />
            </v-col>
            <v-col cols="12" sm="6">
              <v-text-field v-model="reqForm.email" label="Email для документов" type="email" />
            </v-col>
            <v-col cols="12" sm="6">
              <v-text-field v-model="reqForm.phone" label="Телефон ИП" />
            </v-col>
          </v-row>
          <v-btn color="primary" :loading="savingReq" @click="saveRequisites" class="mt-2" prepend-icon="mdi-content-save">
            Сохранить ре��визиты
          </v-btn>
          <v-alert v-if="reqMsg" :type="reqMsgType" density="compact" class="mt-3" closable @click:close="reqMsg = ''">{{ reqMsg }}</v-alert>
        </v-card>

        <!-- Bank Requisites -->
        <v-card class="pa-4">
          <div class="d-flex align-center ga-2 mb-3">
            <v-icon color="primary">mdi-bank</v-icon>
            <div class="text-subtitle-1 font-weight-bold">Банковские реквизиты</div>
            <v-chip v-if="profile.bankRequisites?.verificationStatus" size="small"
              :color="verificationColor(profile.bankRequisites.verificationStatus)">
              {{ verificationLabel(profile.bankRequisites.verificationStatus) }}
            </v-chip>
          </div>
          <v-alert v-if="profile.bankRequisites?.verificationStatus === 'verified'" type="warning" density="compact" class="mb-3" variant="tonal">
            <v-icon class="mr-1">mdi-alert</v-icon>
            Изменение банков��ких реквизитов сбросит статус верификации
          </v-alert>
          <v-row dense>
            <v-col cols="12" sm="6">
              <v-text-field v-model="bankForm.bankName" label="Наименование банка" />
            </v-col>
            <v-col cols="12" sm="6">
              <v-text-field v-model="bankForm.bankBik" label="БИК" />
            </v-col>
            <v-col cols="12" sm="6">
              <v-text-field v-model="bankForm.accountNumber" label="Расчётный счёт" />
            </v-col>
            <v-col cols="12" sm="6">
              <v-text-field v-model="bankForm.correspondentAccount" label="Корр. счёт" />
            </v-col>
            <v-col cols="12">
              <v-text-field v-model="bankForm.beneficiaryName" label="Наименование получателя" />
            </v-col>
          </v-row>
          <v-btn color="primary" :loading="savingBank" @click="saveBankRequisites" class="mt-2" prepend-icon="mdi-content-save">
            Сохранить банковские реквизиты
          </v-btn>
          <v-alert v-if="bankMsg" :type="bankMsgType" density="compact" class="mt-3" closable @click:close="bankMsg = ''">{{ bankMsg }}</v-alert>
        </v-card>
      </v-tabs-window-item>

      <!-- Section 3: Referral Links -->
      <v-tabs-window-item value="referral">
        <v-card class="pa-4">
          <template v-if="profile.referral?.canInvite">
            <div class="d-flex align-center ga-2 mb-3">
              <v-icon color="primary">mdi-link-variant</v-icon>
              <div class="text-subtitle-1 font-weight-bold">Ваша реферальная ссылка</div>
            </div>
            <v-row dense>
              <v-col cols="12" sm="6">
                <v-text-field :model-value="profile.referral.code" label="Реферальный код" readonly>
                  <template #append-inner>
                    <v-btn icon="mdi-content-copy" size="small" variant="text" @click="copyToClipboard(profile.referral.code)" />
                  </template>
                </v-text-field>
              </v-col>
              <v-col cols="12">
                <v-text-field :model-value="profile.referral.link" label="Ссылка для приглашения" readonly>
                  <template #append-inner>
                    <v-btn icon="mdi-content-copy" size="small" variant="text" @click="copyToClipboard(profile.referral.link)" />
                  </template>
                </v-text-field>
              </v-col>
            </v-row>
            <v-alert v-if="copied" type="success" density="compact" class="mt-2">Скопировано в буфер обмена</v-alert>
          </template>
          <v-alert v-else type="info" variant="tonal">
            <v-icon class="mr-1">mdi-information</v-icon>
            Реферальные ссылки доступны только для партнёров со статусом "Активен".
          </v-alert>
        </v-card>
      </v-tabs-window-item>
    </v-tabs-window>

    <v-overlay v-model="loading" class="align-center justify-center" persistent>
      <v-progress-circular indeterminate size="64" />
    </v-overlay>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import api from '../api';
import PageHeader from '../components/PageHeader.vue';

const loading = ref(true);
const tab = ref('info');
const profile = ref({});
const saving = ref(false);
const saveMsg = ref('');
const saveMsgType = ref('success');
const savingPwd = ref(false);
const pwdMsg = ref('');
const pwdMsgType = ref('success');
const savingReq = ref(false);
const reqMsg = ref('');
const reqMsgType = ref('success');
const savingBank = ref(false);
const bankMsg = ref('');
const bankMsgType = ref('success');
const copied = ref(false);
const docFiles = ref({});
const docUploading = ref({});
const docMsg = ref('');
const docMsgType = ref('success');
const uploadedDocs = ref([]);
const addressSameAsRegistration = ref(true);

const documentSlots = [
  { label: 'Паспорт (разворот с фото)', type: 'passportPage1' },
  { label: 'Паспорт (регистрация)', type: 'passportPage2' },
  { label: 'Заявление на получение выплат', type: 'applicationForPayment' },
];

function isDocUploaded(type) {
  return uploadedDocs.value.some(d => d.type === type);
}

async function loadDocuments() {
  try {
    const { data } = await api.get('/documents');
    uploadedDocs.value = data;
  } catch {}
}

async function uploadDocument(type) {
  docUploading.value[type] = true;
  docMsg.value = '';
  try {
    const fd = new FormData();
    fd.append('file', docFiles.value[type]);
    fd.append('type', type);
    await api.post('/documents/upload', fd, { headers: { 'Content-Type': 'multipart/form-data' } });
    docMsg.value = 'Документ загружен';
    docMsgType.value = 'success';
    docFiles.value[type] = null;
    await loadDocuments();
  } catch (e) {
    docMsg.value = e.response?.data?.message || 'Ошибка загрузки';
    docMsgType.value = 'error';
  }
  docUploading.value[type] = false;
}

const genderOptions = [
  { title: 'Мужской', value: 'male' },
  { title: 'Женский', value: 'female' },
];

const form = ref({ phone: '', telegram: '', gender: '', birthDate: '', email: '', country: '', city: '' });
const pwd = ref({ current_password: '', password: '', password_confirmation: '' });
const reqForm = ref({ individualEntrepreneur: '', inn: '', ogrn: '', address: '', email: '', phone: '' });
const bankForm = ref({ bankName: '', bankBik: '', accountNumber: '', correspondentAccount: '', beneficiaryName: '' });

const initials = computed(() => {
  const u = profile.value.user;
  return `${u?.firstName?.[0] || ''}${u?.lastName?.[0] || ''}`.toUpperCase();
});

function verificationColor(status) {
  if (status === 'verified') return 'success';
  if (status === 'rejected') return 'error';
  return 'warning';
}

function verificationLabel(status) {
  if (status === 'verified') return 'Подтверждено';
  if (status === 'rejected') return 'Отклонено';
  return 'На проверке';
}

async function loadProfile() {
  loading.value = true;
  try {
    const { data } = await api.get('/profile');
    profile.value = data;
    const u = data.user || {};
    form.value = {
      firstName: u.firstName, lastName: u.lastName, patronymic: u.patronymic,
      phone: u.phone || '', telegram: u.telegram || '', gender: u.gender || '',
      birthDate: u.birthDate ? u.birthDate.split('T')[0] : '',
      email: u.email || '', country: u.country || '', city: u.city || '',
    };
    const r = data.requisites || {};
    reqForm.value = {
      individualEntrepreneur: r.individualEntrepreneur || '', inn: r.inn || '',
      ogrn: r.ogrn || '', address: r.address || '', actualAddress: r.actualAddress || '',
      email: r.email || '', phone: r.phone || '',
    };
    addressSameAsRegistration.value = !r.actualAddress;
    const b = data.bankRequisites || {};
    bankForm.value = {
      bankName: b.bankName || '', bankBik: b.bankBik || '',
      accountNumber: b.accountNumber || '', correspondentAccount: b.correspondentAccount || '',
      beneficiaryName: b.beneficiaryName || '',
    };
  } catch {}
  loading.value = false;
}

async function saveProfile() {
  saving.value = true;
  saveMsg.value = '';
  try {
    await api.put('/profile', {
      phone: form.value.phone, telegram: form.value.telegram,
      gender: form.value.gender, birthDate: form.value.birthDate,
      email: form.value.email, country: form.value.country, city: form.value.city,
    });
    saveMsg.value = 'Данные сохранены';
    saveMsgType.value = 'success';
  } catch (e) {
    saveMsg.value = e.response?.data?.message || 'Ошибка сохранения';
    saveMsgType.value = 'error';
  }
  saving.value = false;
}

async function changePassword() {
  savingPwd.value = true;
  pwdMsg.value = '';
  try {
    await api.post('/profile/password', pwd.value);
    pwdMsg.value = 'Пароль успешно изменён';
    pwdMsgType.value = 'success';
    pwd.value = { current_password: '', password: '', password_confirmation: '' };
  } catch (e) {
    pwdMsg.value = e.response?.data?.message || 'Ошибка смены пароля';
    pwdMsgType.value = 'error';
  }
  savingPwd.value = false;
}

async function saveRequisites() {
  savingReq.value = true;
  reqMsg.value = '';
  try {
    await api.put('/profile/requisites', reqForm.value);
    reqMsg.value = 'Реквизиты сохранены';
    reqMsgType.value = 'success';
    loadProfile();
  } catch (e) {
    reqMsg.value = e.response?.data?.message || 'Ошибка сохранения';
    reqMsgType.value = 'error';
  }
  savingReq.value = false;
}

async function saveBankRequisites() {
  savingBank.value = true;
  bankMsg.value = '';
  try {
    await api.put('/profile/bank-requisites', bankForm.value);
    bankMsg.value = 'Банковские реквизиты сохранены';
    bankMsgType.value = 'success';
    loadProfile();
  } catch (e) {
    bankMsg.value = e.response?.data?.message || 'Ошибка сохра��ения';
    bankMsgType.value = 'error';
  }
  savingBank.value = false;
}

function copyToClipboard(text) {
  navigator.clipboard.writeText(text);
  copied.value = true;
  setTimeout(() => { copied.value = false; }, 2000);
}

onMounted(() => {
  loadProfile();
  loadDocuments();
});
</script>

// frontend/src/pages/Profile/index.tsx
import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Card, CardContent, Grid, TextField, Button,
  CircularProgress, Alert, Divider, Avatar, Chip, Tabs, Tab,
  Select, MenuItem, InputLabel, FormControl, IconButton, Tooltip,
  Link as MuiLink,
} from '@mui/material';
import {
  Lock, Save, ContentCopy, CheckCircle, Warning,
  Person, AccountBalance, Share,
} from '@mui/icons-material';
import { motion } from 'framer-motion';
import { profileApi, ProfileData, RequisiteData, BankRequisiteData } from '../../api/profile';
import { t } from '../../i18n';

// --- Tab Panel ---
interface TabPanelProps { children?: React.ReactNode; index: number; value: number; }
const TabPanel: React.FC<TabPanelProps> = ({ children, value, index }) => (
  <Box role="tabpanel" hidden={value !== index} sx={{ pt: 3 }}>
    {value === index && children}
  </Box>
);

// --- Requisites Form ---
const RequisitesForm: React.FC<{
  initial: RequisiteData | null;
  onSave: (data: Partial<RequisiteData>) => Promise<void>;
  saving: boolean;
}> = ({ initial, onSave, saving }) => {
  const [form, setForm] = useState({
    individualEntrepreneur: initial?.individualEntrepreneur || '',
    inn: initial?.inn || '',
    ogrn: initial?.ogrn || '',
    address: initial?.address || '',
    email: initial?.email || '',
    phone: initial?.phone || '',
  });

  const set = (field: string) => (e: React.ChangeEvent<HTMLInputElement>) =>
    setForm({ ...form, [field]: e.target.value });

  return (
    <Box>
      {initial?.verified === false && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          Изменение реквизитов приведёт к сбросу верификации. Вы не сможете подать заявку на выплату комиссионных до повторной верификации.
        </Alert>
      )}
      {!initial && (
        <Alert severity="info" sx={{ mb: 2 }}>
          Без верифицированных реквизитов вы не сможете подать заявку на выплату комиссионных.
        </Alert>
      )}
      <Grid container spacing={2}>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="Наименование ИП" value={form.individualEntrepreneur} onChange={set('individualEntrepreneur')} required />
        </Grid>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="ИНН" value={form.inn} onChange={set('inn')} required />
        </Grid>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="ОГРНИП" value={form.ogrn} onChange={set('ogrn')} />
        </Grid>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="Email" value={form.email} onChange={set('email')} />
        </Grid>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="Телефон" value={form.phone} onChange={set('phone')} />
        </Grid>
        <Grid size={{ xs: 12 }}>
          <TextField fullWidth label="Адрес регистрации" value={form.address} onChange={set('address')} multiline rows={2} />
        </Grid>
      </Grid>
      <Button
        variant="contained"
        startIcon={<Save />}
        onClick={() => onSave(form)}
        disabled={saving || !form.individualEntrepreneur || !form.inn}
        sx={{ mt: 2, background: 'linear-gradient(135deg, #4CAF50 0%, #66BB6A 100%)' }}
      >
        {saving ? 'Сохранение...' : 'Сохранить реквизиты'}
      </Button>
    </Box>
  );
};

// --- Bank Requisites Form ---
const BankRequisitesForm: React.FC<{
  initial: BankRequisiteData | null;
  hasRequisites: boolean;
  onSave: (data: Partial<BankRequisiteData>) => Promise<void>;
  saving: boolean;
}> = ({ initial, hasRequisites, onSave, saving }) => {
  const [form, setForm] = useState({
    bankName: initial?.bankName || '',
    bankBik: initial?.bankBik || '',
    accountNumber: initial?.accountNumber || '',
    correspondentAccount: initial?.correspondentAccount || '',
    beneficiaryName: initial?.beneficiaryName || '',
  });

  const set = (field: string) => (e: React.ChangeEvent<HTMLInputElement>) =>
    setForm({ ...form, [field]: e.target.value });

  if (!hasRequisites) {
    return (
      <Alert severity="info">Сначала заполните и сохраните реквизиты ИП.</Alert>
    );
  }

  return (
    <Box>
      {initial?.verified === false && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          Изменение платёжных реквизитов приведёт к сбросу верификации.
        </Alert>
      )}
      {!initial && (
        <Alert severity="info" sx={{ mb: 2 }}>
          Без верифицированных платёжных реквизитов вы не сможете подать заявку на выплату комиссионных.
        </Alert>
      )}
      <Grid container spacing={2}>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="Наименование банка" value={form.bankName} onChange={set('bankName')} required />
        </Grid>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="БИК банка" value={form.bankBik} onChange={set('bankBik')} required />
        </Grid>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="Расчётный счёт" value={form.accountNumber} onChange={set('accountNumber')} required />
        </Grid>
        <Grid size={{ xs: 12, sm: 6 }}>
          <TextField fullWidth label="Корреспондентский счёт" value={form.correspondentAccount} onChange={set('correspondentAccount')} />
        </Grid>
        <Grid size={{ xs: 12 }}>
          <TextField fullWidth label="Получатель" value={form.beneficiaryName} onChange={set('beneficiaryName')} required />
        </Grid>
      </Grid>
      <Button
        variant="contained"
        startIcon={<Save />}
        onClick={() => onSave(form)}
        disabled={saving || !form.bankName || !form.bankBik || !form.accountNumber || !form.beneficiaryName}
        sx={{ mt: 2, background: 'linear-gradient(135deg, #4CAF50 0%, #66BB6A 100%)' }}
      >
        {saving ? 'Сохранение...' : 'Сохранить платёжные реквизиты'}
      </Button>
    </Box>
  );
};

// --- Main Profile ---
const Profile: React.FC = () => {
  const [data, setData] = useState<ProfileData | null>(null);
  const [loading, setLoading] = useState(true);
  const [tab, setTab] = useState(0);
  const [form, setForm] = useState({ phone: '', nicTG: '', gender: '', birthDate: '' });
  const [pwForm, setPwForm] = useState({ current_password: '', password: '', password_confirmation: '' });
  const [msg, setMsg] = useState('');
  const [pwMsg, setPwMsg] = useState('');
  const [saving, setSaving] = useState(false);
  const [reqSaving, setReqSaving] = useState(false);
  const [bankSaving, setBankSaving] = useState(false);
  const [reqMsg, setReqMsg] = useState('');
  const [bankMsg, setBankMsg] = useState('');
  const [copied, setCopied] = useState(false);

  const reload = () => {
    profileApi.get().then((res) => {
      setData(res.data);
      const u = res.data.user;
      setForm({
        phone: u.phone || '',
        nicTG: u.nicTG || '',
        gender: u.gender || '',
        birthDate: u.birthDate ? u.birthDate.split('T')[0] : '',
      });
    }).finally(() => setLoading(false));
  };

  useEffect(() => { reload(); }, []);

  const handleSave = async () => {
    setSaving(true); setMsg('');
    try {
      await profileApi.update(form);
      setMsg('Профиль обновлён');
    } catch { setMsg('Ошибка сохранения'); }
    finally { setSaving(false); }
  };

  const handlePassword = async () => {
    setPwMsg('');
    try {
      await profileApi.changePassword(pwForm);
      setPwMsg('Пароль изменён');
      setPwForm({ current_password: '', password: '', password_confirmation: '' });
    } catch (err: any) {
      setPwMsg(err.response?.data?.message || 'Ошибка');
    }
  };

  const handleReqSave = async (reqData: Partial<any>) => {
    setReqSaving(true); setReqMsg('');
    try {
      await profileApi.updateRequisites(reqData);
      setReqMsg('Реквизиты сохранены');
      reload();
    } catch (err: any) {
      setReqMsg(err.response?.data?.message || 'Ошибка сохранения');
    } finally { setReqSaving(false); }
  };

  const handleBankSave = async (bankData: Partial<any>) => {
    setBankSaving(true); setBankMsg('');
    try {
      await profileApi.updateBankRequisites(bankData);
      setBankMsg('Платёжные реквизиты сохранены');
      reload();
    } catch (err: any) {
      setBankMsg(err.response?.data?.message || 'Ошибка сохранения');
    } finally { setBankSaving(false); }
  };

  const copyReferral = () => {
    if (data?.referral?.referralLink) {
      navigator.clipboard.writeText(data.referral.referralLink);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  if (loading) return <Box sx={{ display: 'flex', justifyContent: 'center', py: 10 }}><CircularProgress /></Box>;
  if (!data) return null;

  const { user, location, consultant, statusInfo, signedDocuments, requisites, bankRequisites, referral } = data;
  const initials = `${user.firstName?.[0] || ''}${user.lastName?.[0] || ''}`.toUpperCase();

  return (
    <Box>
      <Typography variant="h5" sx={{ mb: 3, fontWeight: 600 }}>{t('nav.profile')}</Typography>

      {/* Tabs */}
      <Tabs value={tab} onChange={(_, v) => setTab(v)} sx={{ mb: 0, borderBottom: 1, borderColor: 'divider' }}>
        <Tab icon={<Person />} iconPosition="start" label="Информация" />
        <Tab icon={<AccountBalance />} iconPosition="start" label="Реквизиты" />
        <Tab icon={<Share />} iconPosition="start" label="Реферальные ссылки" />
      </Tabs>

      {/* Tab 1: Partner Info */}
      <TabPanel value={tab} index={0}>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <Card sx={{ mb: 3 }}>
            <CardContent sx={{ p: 3 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 3, mb: 3 }}>
                <Avatar sx={{ width: 72, height: 72, bgcolor: 'primary.main', fontSize: 28 }}>{initials}</Avatar>
                <Box>
                  <Typography variant="h6">{user.lastName} {user.firstName} {user.patronymic}</Typography>
                  <Typography variant="body2" color="text.secondary">{user.email}</Typography>
                  <Box sx={{ display: 'flex', gap: 1, mt: 0.5, flexWrap: 'wrap' }}>
                    {user.role?.split(',').map((r) => (
                      <Chip key={r} label={r.trim()} size="small" variant="outlined" />
                    ))}
                    {statusInfo && (
                      <Chip
                        label={statusInfo.activityName}
                        size="small"
                        color={
                          statusInfo.activityId === 1 ? 'success' :
                          statusInfo.activityId === 4 ? 'info' :
                          statusInfo.activityId === 3 ? 'warning' :
                          statusInfo.activityId === 5 ? 'error' : 'default'
                        }
                      />
                    )}
                  </Box>
                </Box>
              </Box>

              {consultant && (
                <Box sx={{ bgcolor: '#f9f9f9', borderRadius: 2, p: 2, mb: 3 }}>
                  <Grid container spacing={2}>
                    <Grid size={{ xs: 6, sm: 3 }}>
                      <Typography variant="caption" color="text.secondary">ID консультанта</Typography>
                      <Typography variant="body2" sx={{ fontWeight: 600 }}>{consultant.id}</Typography>
                    </Grid>
                    <Grid size={{ xs: 6, sm: 3 }}>
                      <Typography variant="caption" color="text.secondary">Код участника</Typography>
                      <Typography variant="body2" sx={{ fontWeight: 600 }}>{consultant.participantCode || '—'}</Typography>
                    </Grid>
                    <Grid size={{ xs: 6, sm: 3 }}>
                      <Typography variant="caption" color="text.secondary">Наставник</Typography>
                      <Typography variant="body2" sx={{ fontWeight: 600 }}>{consultant.inviterName || '—'}</Typography>
                    </Grid>
                    <Grid size={{ xs: 6, sm: 3 }}>
                      <Typography variant="caption" color="text.secondary">Статус</Typography>
                      <Chip label={consultant.active ? 'Активен' : 'Неактивен'} size="small"
                        color={consultant.active ? 'success' : 'default'} />
                    </Grid>
                  </Grid>
                </Box>
              )}

              {/* Signed documents */}
              {signedDocuments.documents.length > 0 && (
                <Box sx={{ mb: 3 }}>
                  <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 600 }}>Подписанные документы</Typography>
                  {signedDocuments.documents.map((doc) => (
                    <Box key={doc.id} sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.5 }}>
                      {signedDocuments.accepted
                        ? <CheckCircle sx={{ fontSize: 16, color: 'success.main' }} />
                        : <Warning sx={{ fontSize: 16, color: 'warning.main' }} />
                      }
                      <MuiLink href={doc.link} target="_blank" rel="noopener" variant="body2">
                        {doc.name}
                      </MuiLink>
                    </Box>
                  ))}
                  {signedDocuments.acceptedAt && (
                    <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
                      Дата подписания: {new Date(signedDocuments.acceptedAt).toLocaleDateString('ru-RU')}
                    </Typography>
                  )}
                </Box>
              )}

              <Divider sx={{ my: 2 }} />
              <Typography variant="subtitle1" sx={{ mb: 2, fontWeight: 600 }}>Персональные данные</Typography>
              <Alert severity="info" sx={{ mb: 2 }}>
                ФИО заблокировано для самостоятельного изменения. Для смены обратитесь в техподдержку.
              </Alert>

              {msg && <Alert severity={msg.includes('Ошибка') ? 'error' : 'success'} sx={{ mb: 2 }}>{msg}</Alert>}

              <Grid container spacing={2}>
                <Grid size={{ xs: 12, sm: 4 }}>
                  <TextField fullWidth label={t('auth.lastName')} value={user.lastName || ''} disabled />
                </Grid>
                <Grid size={{ xs: 12, sm: 4 }}>
                  <TextField fullWidth label={t('auth.firstName')} value={user.firstName || ''} disabled />
                </Grid>
                <Grid size={{ xs: 12, sm: 4 }}>
                  <TextField fullWidth label={t('auth.patronymic')} value={user.patronymic || ''} disabled />
                </Grid>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <TextField fullWidth label={t('auth.phone')} value={form.phone}
                    onChange={(e) => setForm({ ...form, phone: e.target.value })} />
                </Grid>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <TextField fullWidth label={t('auth.telegram')} value={form.nicTG} placeholder="@username"
                    onChange={(e) => setForm({ ...form, nicTG: e.target.value })} />
                </Grid>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <FormControl fullWidth>
                    <InputLabel>Пол</InputLabel>
                    <Select value={form.gender} label="Пол"
                      onChange={(e) => setForm({ ...form, gender: e.target.value })}>
                      <MenuItem value="">—</MenuItem>
                      <MenuItem value="Мужской">Мужской</MenuItem>
                      <MenuItem value="Женский">Женский</MenuItem>
                    </Select>
                  </FormControl>
                </Grid>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <TextField fullWidth label={t('auth.birthDate')} type="date" value={form.birthDate}
                    onChange={(e) => setForm({ ...form, birthDate: e.target.value })}
                    slotProps={{ inputLabel: { shrink: true } }} />
                </Grid>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <TextField fullWidth label="Налоговое резидентство" value={location.taxResidency || '—'} disabled />
                </Grid>
                <Grid size={{ xs: 12, sm: 6 }}>
                  <TextField fullWidth label={t('auth.city')} value={location.city || '—'} disabled />
                </Grid>
              </Grid>

              <Button variant="contained" startIcon={<Save />} onClick={handleSave} disabled={saving}
                sx={{ mt: 2, background: 'linear-gradient(135deg, #4CAF50 0%, #66BB6A 100%)' }}>
                {saving ? 'Сохранение...' : t('common.save')}
              </Button>
            </CardContent>
          </Card>

          {/* Password change */}
          <Card>
            <CardContent sx={{ p: 3 }}>
              <Typography variant="subtitle1" sx={{ mb: 2, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 1 }}>
                <Lock fontSize="small" /> Изменение пароля
              </Typography>

              {pwMsg && <Alert severity={pwMsg.includes('Ошибка') || pwMsg.includes('неверен') ? 'error' : 'success'} sx={{ mb: 2 }}>{pwMsg}</Alert>}

              <Grid container spacing={2}>
                <Grid size={{ xs: 12, sm: 4 }}>
                  <TextField fullWidth label="Текущий пароль" type="password" value={pwForm.current_password}
                    onChange={(e) => setPwForm({ ...pwForm, current_password: e.target.value })} />
                </Grid>
                <Grid size={{ xs: 12, sm: 4 }}>
                  <TextField fullWidth label="Новый пароль" type="password" value={pwForm.password}
                    onChange={(e) => setPwForm({ ...pwForm, password: e.target.value })} />
                </Grid>
                <Grid size={{ xs: 12, sm: 4 }}>
                  <TextField fullWidth label="Подтверждение" type="password" value={pwForm.password_confirmation}
                    onChange={(e) => setPwForm({ ...pwForm, password_confirmation: e.target.value })} />
                </Grid>
              </Grid>

              <Button variant="outlined" startIcon={<Lock />} onClick={handlePassword} sx={{ mt: 2 }}
                disabled={!pwForm.current_password || !pwForm.password}>
                Сменить пароль
              </Button>
            </CardContent>
          </Card>
        </motion.div>
      </TabPanel>

      {/* Tab 2: Requisites */}
      <TabPanel value={tab} index={1}>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {/* IP Requisites */}
          <Card sx={{ mb: 3 }}>
            <CardContent sx={{ p: 3 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>Реквизиты ИП</Typography>
                {requisites && (
                  <Chip
                    icon={requisites.verified ? <CheckCircle /> : <Warning />}
                    label={requisites.verified ? 'Верифицировано' : 'Ожидает верификации'}
                    size="small"
                    color={requisites.verified ? 'success' : 'warning'}
                    variant="outlined"
                  />
                )}
              </Box>
              {reqMsg && <Alert severity={reqMsg.includes('Ошибка') ? 'error' : 'success'} sx={{ mb: 2 }}>{reqMsg}</Alert>}
              <RequisitesForm initial={requisites} onSave={handleReqSave} saving={reqSaving} />
            </CardContent>
          </Card>

          {/* Bank Requisites */}
          <Card>
            <CardContent sx={{ p: 3 }}>
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
                <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>Платёжные реквизиты</Typography>
                {bankRequisites && (
                  <Chip
                    icon={bankRequisites.verified ? <CheckCircle /> : <Warning />}
                    label={bankRequisites.verified ? 'Верифицировано' : 'Ожидает верификации'}
                    size="small"
                    color={bankRequisites.verified ? 'success' : 'warning'}
                    variant="outlined"
                  />
                )}
              </Box>
              {bankMsg && <Alert severity={bankMsg.includes('Ошибка') ? 'error' : 'success'} sx={{ mb: 2 }}>{bankMsg}</Alert>}
              <BankRequisitesForm
                initial={bankRequisites}
                hasRequisites={!!requisites}
                onSave={handleBankSave}
                saving={bankSaving}
              />
            </CardContent>
          </Card>
        </motion.div>
      </TabPanel>

      {/* Tab 3: Referral Links */}
      <TabPanel value={tab} index={2}>
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <Card>
            <CardContent sx={{ p: 3 }}>
              <Typography variant="subtitle1" sx={{ mb: 2, fontWeight: 600 }}>Реферальные ссылки</Typography>

              {referral?.canInvite ? (
                <Box>
                  <Alert severity="success" sx={{ mb: 3 }}>
                    Ваш статус «Активен» — вы можете приглашать партнёров по реферальной ссылке.
                  </Alert>

                  <Typography variant="body2" color="text.secondary" gutterBottom>Ваш реферальный код</Typography>
                  <Typography variant="h6" sx={{ mb: 2, fontWeight: 600 }}>{referral.referralCode}</Typography>

                  <Typography variant="body2" color="text.secondary" gutterBottom>Реферальная ссылка</Typography>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, bgcolor: '#f5f5f5', borderRadius: 2, p: 2 }}>
                    <Typography variant="body2" sx={{ flexGrow: 1, wordBreak: 'break-all', fontFamily: 'monospace' }}>
                      {referral.referralLink}
                    </Typography>
                    <Tooltip title={copied ? 'Скопировано!' : 'Копировать'}>
                      <IconButton onClick={copyReferral} color={copied ? 'success' : 'default'}>
                        {copied ? <CheckCircle /> : <ContentCopy />}
                      </IconButton>
                    </Tooltip>
                  </Box>
                </Box>
              ) : (
                <Alert severity="info">
                  Реферальные ссылки доступны только в статусе «Активен».
                  {statusInfo && statusInfo.activityId === 4 && (
                    <Typography variant="body2" sx={{ mt: 1 }}>
                      Для активации необходимо набрать {statusInfo.requiredPoints} баллов ЛП в течение {statusInfo.daysRemaining} дней.
                    </Typography>
                  )}
                </Alert>
              )}
            </CardContent>
          </Card>
        </motion.div>
      </TabPanel>
    </Box>
  );
};

export default Profile;
