// frontend/src/pages/Communication/index.tsx
import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Card, CardContent, Chip, CircularProgress,
  Button, TextField, Dialog, DialogTitle, DialogContent, DialogActions,
  FormControl, InputLabel, Select, MenuItem, TablePagination,
  Alert,
} from '@mui/material';
import {
  Chat, Send, MarkEmailRead, Reply, NewReleases,
} from '@mui/icons-material';
import { motion } from 'framer-motion';
import { communicationApi, Message, Category } from '../../api/communication';
import { t } from '../../i18n';

const Communication: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [total, setTotal] = useState(0);
  const [unreadCount, setUnreadCount] = useState(0);
  const [page, setPage] = useState(0);
  const [categoryFilter, setCategoryFilter] = useState('');
  const [loading, setLoading] = useState(true);

  // Send dialog
  const [sendOpen, setSendOpen] = useState(false);
  const [sendCategory, setSendCategory] = useState<number>(0);
  const [sendMessage, setSendMessage] = useState('');
  const [sending, setSending] = useState(false);

  // Categories
  const [categories, setCategories] = useState<Category[]>([]);

  useEffect(() => {
    communicationApi.categories().then((r) => setCategories(r.data)).catch(() => {});
  }, []);

  const loadMessages = () => {
    setLoading(true);
    const params: any = { page: page + 1 };
    if (categoryFilter) params.category = categoryFilter;

    communicationApi.list(params)
      .then((res) => {
        setMessages(res.data.data);
        setTotal(res.data.total);
        setUnreadCount(res.data.unreadCount);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  };

  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { loadMessages(); }, [page, categoryFilter]);

  const handleMarkRead = async (id: number) => {
    await communicationApi.markRead(id);
    loadMessages();
  };

  const handleSend = async () => {
    if (!sendCategory || !sendMessage.trim()) return;
    setSending(true);
    try {
      await communicationApi.send({ category: sendCategory, message: sendMessage });
      setSendOpen(false);
      setSendMessage('');
      setSendCategory(0);
      loadMessages();
    } catch {}
    setSending(false);
  };

  const openReply = (msg: Message) => {
    setSendCategory(msg.category);
    setSendMessage('');
    setSendOpen(true);
  };

  const formatDate = (iso: string) => {
    const d = new Date(iso);
    return d.toLocaleDateString('ru-RU') + ' ' + d.toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' });
  };

  return (
    <Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
        <Chat sx={{ fontSize: 32, color: 'primary.main' }} />
        <Typography variant="h5" sx={{ fontWeight: 600 }}>{t('nav.communication')}</Typography>
        {unreadCount > 0 && (
          <Chip label={`${unreadCount} новых`} color="error" size="small" />
        )}
      </Box>

      {/* Filters + Send */}
      <Card sx={{ mb: 2 }}>
        <CardContent sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center', py: 2 }}>
          <FormControl size="small" sx={{ minWidth: 200 }}>
            <InputLabel>Категория</InputLabel>
            <Select value={categoryFilter} label="Категория"
              onChange={(e) => { setCategoryFilter(e.target.value); setPage(0); }}>
              <MenuItem value="">Все</MenuItem>
              {categories.map((c) => <MenuItem key={c.id} value={c.id}>{c.title}</MenuItem>)}
            </Select>
          </FormControl>
          <Box sx={{ flexGrow: 1 }} />
          <Button variant="contained" startIcon={<Send />} onClick={() => setSendOpen(true)}>
            Написать
          </Button>
        </CardContent>
      </Card>

      {/* Messages */}
      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 5 }}><CircularProgress /></Box>
      ) : messages.length === 0 ? (
        <Alert severity="info">Сообщений пока нет</Alert>
      ) : (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          {messages.map((msg) => (
            <Card key={msg.id} sx={{ mb: 1.5, borderLeft: msg.isIncoming ? '4px solid #2196F3' : '4px solid #4CAF50' }}>
              <CardContent sx={{ py: 2, '&:last-child': { pb: 2 } }}>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 1 }}>
                  <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', flexWrap: 'wrap' }}>
                    <Chip
                      label={msg.isIncoming ? 'От DS' : 'Вы'}
                      size="small"
                      color={msg.isIncoming ? 'primary' : 'success'}
                      variant="outlined"
                    />
                    {msg.categoryTitle && (
                      <Chip label={msg.categoryTitle} size="small" variant="outlined" />
                    )}
                    {msg.isIncoming && !msg.read && (
                      <Chip icon={<NewReleases />} label="Новое" size="small" color="error" />
                    )}
                  </Box>
                  <Typography variant="caption" color="text.secondary">
                    {formatDate(msg.date)}
                  </Typography>
                </Box>

                <Typography variant="body2" sx={{ whiteSpace: 'pre-wrap', mb: 1 }}>
                  {msg.message}
                </Typography>

                <Box sx={{ display: 'flex', gap: 1 }}>
                  {msg.isIncoming && !msg.read && (
                    <Button size="small" startIcon={<MarkEmailRead />}
                      onClick={() => handleMarkRead(msg.id)}>
                      Прочитано
                    </Button>
                  )}
                  {msg.isIncoming && (
                    <Button size="small" startIcon={<Reply />}
                      onClick={() => openReply(msg)}>
                      Ответить
                    </Button>
                  )}
                </Box>
              </CardContent>
            </Card>
          ))}

          <TablePagination
            component="div" count={total} page={page} rowsPerPage={25}
            onPageChange={(_, p) => setPage(p)} rowsPerPageOptions={[25]}
            labelDisplayedRows={({ from, to, count }) => `${from}–${to} из ${count}`}
          />
        </motion.div>
      )}

      {/* Send dialog */}
      <Dialog open={sendOpen} onClose={() => setSendOpen(false)} maxWidth="sm" fullWidth>
        <DialogTitle>Новое сообщение</DialogTitle>
        <DialogContent>
          <FormControl fullWidth sx={{ mt: 1, mb: 2 }}>
            <InputLabel>Категория</InputLabel>
            <Select value={sendCategory || ''} label="Категория"
              onChange={(e) => setSendCategory(Number(e.target.value))}>
              {categories.map((c) => <MenuItem key={c.id} value={c.id}>{c.title}</MenuItem>)}
            </Select>
          </FormControl>
          <TextField
            fullWidth multiline rows={4}
            label="Сообщение"
            value={sendMessage}
            onChange={(e) => setSendMessage(e.target.value)}
            placeholder="Введите текст сообщения..."
          />
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setSendOpen(false)}>{t('common.cancel')}</Button>
          <Button variant="contained" startIcon={<Send />}
            onClick={handleSend}
            disabled={sending || !sendCategory || !sendMessage.trim()}>
            {sending ? 'Отправка...' : 'Отправить'}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default Communication;

// resources/js/pages/Communication.vue
<template>
  <div>
    <div class="d-flex justify-space-between align-center mb-4 flex-wrap ga-2">
      <div class="d-flex align-center ga-2">
        <v-icon size="32" color="primary">mdi-chat</v-icon>
        <h5 class="text-h5 font-weight-bold">Коммуникация</h5>
        <v-badge v-if="unreadCount > 0" :content="unreadCount" color="error" inline />
      </div>
      <v-btn color="primary" prepend-icon="mdi-pencil" @click="openSendDialog">Написать</v-btn>
    </div>

    <v-card class="mb-3 pa-3">
      <v-select v-model="categoryFilter" :items="categoryOptions" label="Категория" density="compact" variant="outlined"
        clearable hide-details style="max-width:260px" @update:model-value="loadMessages" />
    </v-card>

    <v-card :loading="loading">
      <v-list lines="three">
        <template v-for="msg in messages" :key="msg.id">
          <v-list-item>
            <template #prepend>
              <v-chip size="small" :color="msg.direction === 'ds2p' ? 'blue' : 'green'" class="mr-2" variant="flat">
                {{ msg.direction === 'ds2p' ? 'От DS' : 'Вы' }}
              </v-chip>
            </template>
            <v-list-item-title class="d-flex align-center ga-2">
              <span class="font-weight-medium">{{ msg.category || 'Без категории' }}</span>
              <v-chip v-if="msg.direction === 'ds2p' && !msg.readAt" size="x-small" color="error">Новое</v-chip>
              <span class="text-caption text-medium-emphasis ml-auto">{{ msg.createdAt }}</span>
            </v-list-item-title>
            <v-list-item-subtitle class="mt-1" style="white-space: pre-line">{{ msg.message }}</v-list-item-subtitle>
            <template #append>
              <div class="d-flex flex-column ga-1">
                <v-btn v-if="msg.direction === 'ds2p' && !msg.readAt" size="x-small" variant="outlined" color="primary"
                  @click="markRead(msg)">Прочитано</v-btn>
                <v-btn v-if="msg.direction === 'ds2p'" size="x-small" variant="outlined"
                  @click="openReply(msg)">Ответить</v-btn>
              </div>
            </template>
          </v-list-item>
          <v-divider />
        </template>
        <v-list-item v-if="!messages.length && !loading">
          <v-list-item-title class="text-center text-medium-emphasis">Сообщений нет</v-list-item-title>
        </v-list-item>
      </v-list>

      <div v-if="totalPages > 1" class="d-flex justify-center pa-3">
        <v-pagination v-model="page" :length="totalPages" density="compact" @update:model-value="loadMessages" />
      </div>
    </v-card>

    <!-- Send / Reply Dialog -->
    <v-dialog v-model="sendDialog" max-width="600" persistent>
      <v-card>
        <v-card-title>{{ replyTo ? 'Ответ на сообщение' : 'Новое сообщение' }}</v-card-title>
        <v-card-text>
          <v-select v-model="sendForm.category_id" :items="categoryOptions" label="Категория" density="compact"
            class="mb-3" />
          <v-textarea v-model="sendForm.message" label="Сообщение" rows="5" auto-grow />
          <v-alert v-if="sendError" type="error" density="compact" class="mt-2">{{ sendError }}</v-alert>
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="sendDialog = false">Отмена</v-btn>
          <v-btn color="primary" :loading="sending" @click="sendMessage">Отправить</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import api from '../api';

const loading = ref(false);
const messages = ref([]);
const page = ref(1);
const totalPages = ref(1);
const unreadCount = ref(0);
const categoryFilter = ref(null);
const categoryOptions = ref([]);
const sendDialog = ref(false);
const sending = ref(false);
const sendError = ref('');
const replyTo = ref(null);
const sendForm = ref({ category_id: null, message: '' });

async function loadMessages() {
  loading.value = true;
  try {
    const params = { page: page.value };
    if (categoryFilter.value) params.category = categoryFilter.value;
    const { data } = await api.get('/communication', { params });
    messages.value = data.data;
    totalPages.value = data.last_page || 1;
  } catch {}
  loading.value = false;
}

async function loadUnreadCount() {
  try {
    const { data } = await api.get('/communication/unread-count');
    unreadCount.value = data.count ?? data;
  } catch {}
}

async function loadCategories() {
  try {
    const { data } = await api.get('/communication/categories');
    categoryOptions.value = data.map(c => ({ title: c.name, value: c.id }));
  } catch {}
}

async function markRead(msg) {
  try {
    await api.post(`/communication/${msg.id}/read`);
    msg.readAt = new Date().toISOString();
    loadUnreadCount();
  } catch {}
}

function openSendDialog() {
  replyTo.value = null;
  sendForm.value = { category_id: null, message: '' };
  sendError.value = '';
  sendDialog.value = true;
}

function openReply(msg) {
  replyTo.value = msg;
  sendForm.value = { category_id: msg.category_id || null, message: '' };
  sendError.value = '';
  sendDialog.value = true;
}

async function sendMessage() {
  sending.value = true;
  sendError.value = '';
  try {
    await api.post('/communication', {
      category_id: sendForm.value.category_id,
      message: sendForm.value.message,
      reply_to: replyTo.value?.id || null,
    });
    sendDialog.value = false;
    loadMessages();
    loadUnreadCount();
  } catch (e) {
    sendError.value = e.response?.data?.message || 'Ошибка отправки';
  }
  sending.value = false;
}

onMounted(() => {
  loadMessages();
  loadUnreadCount();
  loadCategories();
});
</script>
