// frontend/src/pages/Contests/index.tsx
import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Card, CardContent, Grid, Chip, CircularProgress,
  FormControl, InputLabel, Select, MenuItem, Button, Alert,
} from '@mui/material';
import { EmojiEvents, OpenInNew } from '@mui/icons-material';
import { motion } from 'framer-motion';
import api from '../../api/client';
import { t } from '../../i18n';

interface Contest {
  id: number; name: string; description: string | null;
  typeName: string | null; status: number; statusLabel: string;
  start: string | null; end: string | null;
  numberOfWinners: number | null;
  resultsPublicationDate: string | null;
  presentation: string | null;
}

const statusColor = (s: number): 'success' | 'warning' | 'default' => {
  if (s === 1) return 'success';
  if (s === 2) return 'warning';
  return 'default';
};

const fmtDate = (s: string | null) => s ? new Date(s).toLocaleDateString('ru-RU') : '—';

const Contests: React.FC = () => {
  const [contests, setContests] = useState<Contest[]>([]);
  const [types, setTypes] = useState<{ id: number; name: string }[]>([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState('');
  const [typeFilter, setTypeFilter] = useState('');

  useEffect(() => {
    setLoading(true);
    const params: any = {};
    if (statusFilter) params.status = statusFilter;
    if (typeFilter) params.type = typeFilter;

    api.get('/contests', { params })
      .then((res) => {
        setContests(res.data.contests);
        setTypes(res.data.types || []);
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [statusFilter, typeFilter]);

  return (
    <Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
        <EmojiEvents sx={{ fontSize: 32, color: 'primary.main' }} />
        <Typography variant="h5" sx={{ fontWeight: 600 }}>{t('nav.contestList')}</Typography>
        <Chip label={`${contests.length}`} color="primary" size="small" />
      </Box>

      {/* Filters */}
      <Card sx={{ mb: 3 }}>
        <CardContent sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', py: 2 }}>
          <FormControl size="small" sx={{ minWidth: 160 }}>
            <InputLabel>Статус</InputLabel>
            <Select value={statusFilter} label="Статус"
              onChange={(e) => setStatusFilter(e.target.value)}>
              <MenuItem value="">Все</MenuItem>
              <MenuItem value="1">Активные</MenuItem>
              <MenuItem value="2">Завершённые</MenuItem>
              <MenuItem value="3">Архив</MenuItem>
            </Select>
          </FormControl>
          {types.length > 0 && (
            <FormControl size="small" sx={{ minWidth: 160 }}>
              <InputLabel>Тип</InputLabel>
              <Select value={typeFilter} label="Тип"
                onChange={(e) => setTypeFilter(e.target.value)}>
                <MenuItem value="">Все</MenuItem>
                {types.map((t) => <MenuItem key={t.id} value={t.id}>{t.name}</MenuItem>)}
              </Select>
            </FormControl>
          )}
        </CardContent>
      </Card>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 5 }}><CircularProgress /></Box>
      ) : contests.length === 0 ? (
        <Alert severity="info">Конкурсов не найдено</Alert>
      ) : (
        <Grid container spacing={3}>
          {contests.map((c, idx) => (
            <Grid size={{ xs: 12, md: 6 }} key={c.id}>
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: idx * 0.05 }}
              >
                <Card sx={{
                  height: '100%',
                  borderLeft: c.status === 1 ? '4px solid #4CAF50' : c.status === 2 ? '4px solid #FF9800' : '4px solid #9E9E9E',
                }}>
                  <CardContent sx={{ p: 3 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 1 }}>
                      <Typography variant="h6" sx={{ fontWeight: 600 }}>{c.name}</Typography>
                      <Chip label={c.statusLabel} size="small" color={statusColor(c.status)} />
                    </Box>

                    {c.typeName && (
                      <Chip label={c.typeName} size="small" variant="outlined" sx={{ mb: 1 }} />
                    )}

                    {c.description && (
                      <Typography variant="body2" color="text.secondary" sx={{ mb: 2, whiteSpace: 'pre-line' }}>
                        {c.description.length > 200 ? c.description.slice(0, 200) + '...' : c.description}
                      </Typography>
                    )}

                    <Grid container spacing={1} sx={{ mb: 1 }}>
                      <Grid size={{ xs: 6 }}>
                        <Typography variant="caption" color="text.secondary">Начало</Typography>
                        <Typography variant="body2">{fmtDate(c.start)}</Typography>
                      </Grid>
                      <Grid size={{ xs: 6 }}>
                        <Typography variant="caption" color="text.secondary">Окончание</Typography>
                        <Typography variant="body2">{fmtDate(c.end)}</Typography>
                      </Grid>
                      {c.numberOfWinners && (
                        <Grid size={{ xs: 6 }}>
                          <Typography variant="caption" color="text.secondary">Победителей</Typography>
                          <Typography variant="body2">{c.numberOfWinners}</Typography>
                        </Grid>
                      )}
                      {c.resultsPublicationDate && (
                        <Grid size={{ xs: 6 }}>
                          <Typography variant="caption" color="text.secondary">Результаты</Typography>
                          <Typography variant="body2">{fmtDate(c.resultsPublicationDate)}</Typography>
                        </Grid>
                      )}
                    </Grid>

                    {c.presentation && (
                      <Button
                        size="small" variant="outlined" startIcon={<OpenInNew />}
                        href={c.presentation} target="_blank" rel="noopener"
                        sx={{ mt: 1 }}
                      >
                        Презентация
                      </Button>
                    )}
                  </CardContent>
                </Card>
              </motion.div>
            </Grid>
          ))}
        </Grid>
      )}
    </Box>
  );
};

export default Contests;

// resources/js/pages/Contests.vue
<template>
  <div>
    <PageHeader title="Список конкурсов и событий" icon="mdi-trophy" />

    <v-card class="mb-3 pa-3">
      <div class="d-flex ga-2 flex-wrap align-center">
        <v-select v-model="filters.status" :items="statusFilterOptions" label="Статус"
          clearable hide-details style="max-width:200px" @update:model-value="loadData" />
        <v-select v-model="filters.type" :items="typeFilterOptions" label="Тип"
          item-title="title" item-value="value"
          clearable hide-details style="max-width:240px" @update:model-value="loadData" />
      </div>
    </v-card>

    <v-row>
      <v-col v-for="contest in contests" :key="contest.id" cols="12" sm="6" md="4">
        <v-card class="pa-4 d-flex flex-column" height="100%"
          :style="{ borderLeft: `4px solid ${contestBorderColor(contest.status)}` }">
          <div class="d-flex justify-space-between align-center mb-2">
            <v-chip size="small" :color="contestStatusColor(contest.status)">
              {{ contestStatusLabel(contest.status) }}
            </v-chip>
            <span v-if="contest.typeName" class="text-caption text-medium-emphasis">{{ contest.typeName }}</span>
          </div>
          <div class="text-subtitle-1 font-weight-bold mb-1">{{ contest.name }}</div>
          <div class="text-body-2 text-medium-emphasis flex-grow-1 mb-2">{{ contest.description }}</div>
          <div class="text-body-2 mb-1">
            <span class="text-medium-emphasis">Период:</span> {{ fmtDate(contest.start) }} — {{ fmtDate(contest.end) }}
          </div>
          <div v-if="contest.numberOfWinners" class="text-caption text-medium-emphasis">
            Победителей: {{ contest.numberOfWinners }}
          </div>
          <v-btn v-if="contest.presentation" variant="outlined" size="small" color="primary"
            :href="contest.presentation" target="_blank" class="mt-3" prepend-icon="mdi-presentation">
            Презентация
          </v-btn>
        </v-card>
      </v-col>
    </v-row>

    <v-card v-if="!contests.length && !loading" class="pa-8 text-center">
      <v-icon size="64" color="grey-lighten-1" class="mb-3">mdi-trophy-outline</v-icon>
      <div class="text-h6 text-medium-emphasis mb-1">Конкурсов и событий пока нет</div>
      <div class="text-body-2 text-medium-emphasis">Следите за обновлениями — скоро здесь появятся новые конкурсы и события</div>
    </v-card>

    <v-overlay v-model="loading" class="align-center justify-center" persistent>
      <v-progress-circular indeterminate size="64" />
    </v-overlay>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import api from '../api';
import PageHeader from '../components/PageHeader.vue';
import { fmtDate } from '../composables/useDesign';

const loading = ref(true);
const contests = ref([]);
const filters = ref({ status: null, type: null });

const statusFilterOptions = [
  { title: 'Активный', value: 1 },
  { title: 'Завершён', value: 2 },
  { title: 'Архив', value: 3 },
];

const typeFilterOptions = ref([]);

function contestStatusColor(status) {
  if (status === 1) return 'success';
  if (status === 2) return 'orange';
  return 'grey';
}

function contestBorderColor(status) {
  if (status === 1) return '#4CAF50';
  if (status === 2) return '#FF9800';
  return '#9E9E9E';
}

function contestStatusLabel(status) {
  if (status === 1) return 'Активный';
  if (status === 2) return 'Завершён';
  return 'Архив';
}

async function loadData() {
  loading.value = true;
  try {
    const params = {};
    if (filters.value.status) params.status = filters.value.status;
    if (filters.value.type) params.type = filters.value.type;
    const { data } = await api.get('/contests', { params });
    if (Array.isArray(data)) {
      contests.value = data;
    } else {
      contests.value = data.contests || data.data || [];
      if (data.types) typeFilterOptions.value = data.types.map(t => ({ title: t.name, value: t.id }));
    }
  } catch {}
  loading.value = false;
}

onMounted(loadData);
</script>
