// frontend/src/pages/Structure/index.tsx
import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Card, CardContent, Chip, CircularProgress,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow,
  Paper, IconButton, TextField, InputAdornment, Grid,
  FormControl, InputLabel, Select, MenuItem, Button, Collapse,
} from '@mui/material';
import {
  AccountTree, Search, KeyboardArrowDown, KeyboardArrowRight,
  FilterList, ExpandMore, ExpandLess,
} from '@mui/icons-material';
import { motion } from 'framer-motion';
import api from '../../api/client';
import { t } from '../../i18n';

interface StructureMember {
  id: number;
  personName: string;
  active: boolean;
  activityId: number;
  activityName: string;
  qualification: { level: number; title: string } | null;
  personalVolume: number;
  groupVolume: number;
  groupVolumeCumulative: number;
  clientCount: number;
  contractCount: number;
  hasChildren: boolean;
  birthDate: string | null;
  city: string | null;
  dateActivity: string | null;
}

interface FilterOption { id: number; name?: string; level?: number; title?: string; }

const fmt = (n: number) => n.toLocaleString('ru-RU', { minimumFractionDigits: 2 });

const activityColor = (id: number): 'success' | 'info' | 'warning' | 'error' | 'default' => {
  if (id === 1) return 'success';   // Активный
  if (id === 4) return 'info';      // Зарегистрирован
  if (id === 3) return 'warning';   // Терминирован
  if (id === 5) return 'error';     // Исключен
  return 'default';
};

const MemberRow: React.FC<{ member: StructureMember; depth: number }> = ({ member, depth }) => {
  const [open, setOpen] = useState(false);
  const [children, setChildren] = useState<StructureMember[]>([]);
  const [loading, setLoading] = useState(false);

  const toggleChildren = async () => {
    if (!open && children.length === 0 && member.hasChildren) {
      setLoading(true);
      try {
        const res = await api.get(`/structure/${member.id}/children`);
        setChildren(res.data.data);
      } catch {}
      setLoading(false);
    }
    setOpen(!open);
  };

  return (
    <>
      <TableRow hover sx={{ bgcolor: depth > 0 ? `rgba(0,0,0,${0.02 * depth})` : 'inherit' }}>
        <TableCell sx={{ pl: 2 + depth * 3 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
            {member.hasChildren ? (
              <IconButton size="small" onClick={toggleChildren}>
                {loading ? <CircularProgress size={16} /> : open ? <KeyboardArrowDown /> : <KeyboardArrowRight />}
              </IconButton>
            ) : (
              <Box sx={{ width: 32 }} />
            )}
            <Typography variant="body2" sx={{ fontWeight: 600 }}>{member.personName}</Typography>
          </Box>
        </TableCell>
        <TableCell>
          {member.qualification
            ? <Chip label={`${member.qualification.level} [${member.qualification.title}]`} size="small" variant="outlined" />
            : '—'
          }
        </TableCell>
        <TableCell>
          <Chip label={member.activityName} size="small" color={activityColor(member.activityId)} />
        </TableCell>
        <TableCell>{member.dateActivity || '—'}</TableCell>
        <TableCell align="right">{fmt(member.personalVolume)}</TableCell>
        <TableCell align="right">{fmt(member.groupVolume)}</TableCell>
        <TableCell align="right">{fmt(member.groupVolumeCumulative)}</TableCell>
        <TableCell align="center">{member.clientCount}</TableCell>
      </TableRow>

      {open && children.map((child) => (
        <MemberRow key={child.id} member={child} depth={depth + 1} />
      ))}
    </>
  );
};

const TeamStructure: React.FC = () => {
  const [members, setMembers] = useState<StructureMember[]>([]);
  const [loading, setLoading] = useState(true);
  const [filtersOpen, setFiltersOpen] = useState(false);

  // Filters
  const [search, setSearch] = useState('');
  const [activity, setActivity] = useState<string[]>([]);
  const [qualification, setQualification] = useState<string[]>([]);
  const [city, setCity] = useState('');
  const [lpMin, setLpMin] = useState('');
  const [lpMax, setLpMax] = useState('');
  const [gpMin, setGpMin] = useState('');
  const [gpMax, setGpMax] = useState('');
  const [ngpMin, setNgpMin] = useState('');
  const [ngpMax, setNgpMax] = useState('');

  // Filter options
  const [activityOptions, setActivityOptions] = useState<FilterOption[]>([]);
  const [qualificationOptions, setQualificationOptions] = useState<FilterOption[]>([]);

  useEffect(() => {
    api.get('/structure/activity-statuses').then((r) => setActivityOptions(r.data)).catch(() => {});
    api.get('/structure/qualification-levels').then((r) => setQualificationOptions(r.data)).catch(() => {});
  }, []);

  useEffect(() => {
    setLoading(true);
    const params: any = {};
    if (search) params.search = search;
    if (activity.length) params.activity = activity.join(',');
    if (qualification.length) params.qualification = qualification.join(',');
    if (city) params.city = city;
    if (lpMin) params.lp_min = lpMin;
    if (lpMax) params.lp_max = lpMax;
    if (gpMin) params.gp_min = gpMin;
    if (gpMax) params.gp_max = gpMax;
    if (ngpMin) params.ngp_min = ngpMin;
    if (ngpMax) params.ngp_max = ngpMax;

    api.get('/structure', { params })
      .then((res) => setMembers(res.data.data))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [search, activity, qualification, city, lpMin, lpMax, gpMin, gpMax, ngpMin, ngpMax]);

  const clearFilters = () => {
    setSearch(''); setActivity([]); setQualification([]); setCity('');
    setLpMin(''); setLpMax(''); setGpMin(''); setGpMax('');
    setNgpMin(''); setNgpMax('');
  };

  return (
    <Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
        <AccountTree sx={{ fontSize: 32, color: 'primary.main' }} />
        <Typography variant="h5" sx={{ fontWeight: 600 }}>{t('nav.teamStructure')}</Typography>
        <Chip label={`${members.length}`} color="primary" size="small" />
      </Box>

      {/* Filters */}
      <Card sx={{ mb: 2 }}>
        <CardContent sx={{ py: 2 }}>
          <Grid container spacing={2} sx={{ alignItems: 'center' }}>
            <Grid size={{ xs: 12, sm: 5 }}>
              <TextField
                fullWidth size="small" placeholder="Поиск по ФИО партнёра..." value={search}
                onChange={(e) => setSearch(e.target.value)}
                slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search /></InputAdornment> } }}
              />
            </Grid>
            <Grid size={{ xs: 6, sm: 3 }}>
              <FormControl fullWidth size="small">
                <InputLabel>Статус</InputLabel>
                <Select
                  multiple value={activity} label="Статус"
                  onChange={(e) => setActivity(typeof e.target.value === 'string' ? e.target.value.split(',') : e.target.value as string[])}
                  renderValue={(sel) => sel.map((id) => activityOptions.find((o) => String(o.id) === id)?.name).join(', ')}
                >
                  {activityOptions.map((o) => <MenuItem key={o.id} value={String(o.id)}>{o.name}</MenuItem>)}
                </Select>
              </FormControl>
            </Grid>
            <Grid size={{ xs: 6, sm: 2 }}>
              <FormControl fullWidth size="small">
                <InputLabel>Квалификация</InputLabel>
                <Select
                  multiple value={qualification} label="Квалификация"
                  onChange={(e) => setQualification(typeof e.target.value === 'string' ? e.target.value.split(',') : e.target.value as string[])}
                  renderValue={(sel) => sel.map((l) => qualificationOptions.find((o) => String(o.level) === l)?.title).join(', ')}
                >
                  {qualificationOptions.map((o) => <MenuItem key={o.id} value={String(o.level)}>{o.level}. {o.title}</MenuItem>)}
                </Select>
              </FormControl>
            </Grid>
            <Grid size={{ xs: 12, sm: 2 }}>
              <Button
                fullWidth variant="outlined" size="small"
                startIcon={filtersOpen ? <ExpandLess /> : <ExpandMore />}
                onClick={() => setFiltersOpen(!filtersOpen)}
              >
                <FilterList sx={{ mr: 0.5 }} /> Ещё
              </Button>
            </Grid>
          </Grid>

          <Collapse in={filtersOpen}>
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid size={{ xs: 12, sm: 3 }}>
                <TextField fullWidth size="small" label="Город" value={city}
                  onChange={(e) => setCity(e.target.value)} />
              </Grid>
              <Grid size={{ xs: 6, sm: 1.5 }}>
                <TextField fullWidth size="small" label="ЛП от" type="number" value={lpMin}
                  onChange={(e) => setLpMin(e.target.value)} />
              </Grid>
              <Grid size={{ xs: 6, sm: 1.5 }}>
                <TextField fullWidth size="small" label="ЛП до" type="number" value={lpMax}
                  onChange={(e) => setLpMax(e.target.value)} />
              </Grid>
              <Grid size={{ xs: 6, sm: 1.5 }}>
                <TextField fullWidth size="small" label="ГП от" type="number" value={gpMin}
                  onChange={(e) => setGpMin(e.target.value)} />
              </Grid>
              <Grid size={{ xs: 6, sm: 1.5 }}>
                <TextField fullWidth size="small" label="ГП до" type="number" value={gpMax}
                  onChange={(e) => setGpMax(e.target.value)} />
              </Grid>
              <Grid size={{ xs: 6, sm: 1.5 }}>
                <TextField fullWidth size="small" label="НГП от" type="number" value={ngpMin}
                  onChange={(e) => setNgpMin(e.target.value)} />
              </Grid>
              <Grid size={{ xs: 6, sm: 1.5 }}>
                <TextField fullWidth size="small" label="НГП до" type="number" value={ngpMax}
                  onChange={(e) => setNgpMax(e.target.value)} />
              </Grid>
            </Grid>
            <Box sx={{ mt: 1 }}>
              <Button size="small" onClick={clearFilters}>Сбросить фильтры</Button>
            </Box>
          </Collapse>
        </CardContent>
      </Card>

      {loading ? (
        <Box sx={{ display: 'flex', justifyContent: 'center', py: 5 }}><CircularProgress /></Box>
      ) : (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
          <TableContainer component={Paper}>
            <Table size="small">
              <TableHead>
                <TableRow sx={{ bgcolor: '#f5f5f5' }}>
                  <TableCell>Партнёр</TableCell>
                  <TableCell>Квалификация</TableCell>
                  <TableCell>Статус</TableCell>
                  <TableCell>Дата смены</TableCell>
                  <TableCell align="right">ЛП</TableCell>
                  <TableCell align="right">ГП</TableCell>
                  <TableCell align="right">НГП</TableCell>
                  <TableCell align="center">Клиенты</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {members.map((m) => (
                  <MemberRow key={m.id} member={m} depth={0} />
                ))}
                {members.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={8} sx={{ textAlign: 'center', py: 4, color: 'text.secondary' }}>
                      Нет партнёров в структуре
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </TableContainer>
        </motion.div>
      )}
    </Box>
  );
};

export default TeamStructure;

// resources/js/pages/Structure.vue
<template>
  <div>
    <PageHeader title="Структура моей команды" icon="mdi-sitemap" />

    <v-card class="mb-3 pa-3">
      <div class="d-flex ga-2 flex-wrap align-center">
        <v-text-field v-model="filters.search" placeholder="ФИО партнёра..."
          rounded prepend-inner-icon="mdi-magnify" clearable hide-details style="max-width:240px" @update:model-value="debouncedLoad" />
        <v-select v-model="filters.qualification" :items="qualificationOptions" label="Квалификация"
          multiple clearable hide-details style="max-width:240px" @update:model-value="loadData" />
        <v-select v-model="filters.levels" :items="qualificationOptions" label="Уровни"
          multiple clearable hide-details style="max-width:240px" @update:model-value="loadData" />
        <v-select v-model="filters.status" :items="statusOptions" label="Статус"
          multiple clearable hide-details style="max-width:240px" @update:model-value="loadData" />
        <v-btn variant="text" size="small" :prepend-icon="showAdvanced ? 'mdi-chevron-up' : 'mdi-chevron-down'"
          @click="showAdvanced = !showAdvanced">Доп. фильтры</v-btn>
        <v-chip v-if="activeFilterCount > 0" size="small" color="info" variant="tonal" class="ml-1">
          {{ activeFilterCount }} {{ activeFilterCount === 1 ? 'фильтр' : activeFilterCount < 5 ? 'фильтра' : 'фильтров' }}
        </v-chip>
        <v-btn v-if="activeFilterCount > 0" size="small" variant="text" color="secondary"
          prepend-icon="mdi-filter-remove" @click="resetFilters">Сбросить</v-btn>
      </div>
      <v-expand-transition>
        <div v-if="showAdvanced" class="d-flex ga-2 flex-wrap align-center mt-3">
          <v-text-field v-model="filters.birth_date_from" label="Дата рождения с" type="date"
            hide-details style="max-width:170px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.birth_date_to" label="Дата рождения по" type="date"
            hide-details style="max-width:170px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.city" placeholder="Город"
            hide-details style="max-width:180px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.lp_min" placeholder="ЛП от" type="number"
            hide-details style="max-width:110px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.lp_max" placeholder="ЛП до" type="number"
            hide-details style="max-width:110px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.gp_min" placeholder="ГП от" type="number"
            hide-details style="max-width:110px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.gp_max" placeholder="ГП до" type="number"
            hide-details style="max-width:110px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.ngp_min" placeholder="НГП от" type="number"
            hide-details style="max-width:110px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.ngp_max" placeholder="НГП до" type="number"
            hide-details style="max-width:110px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.termination_from" label="Терминация с" type="date"
            hide-details style="max-width:170px" @update:model-value="debouncedLoad" />
          <v-text-field v-model="filters.termination_to" label="Терминация по" type="date"
            hide-details style="max-width:170px" @update:model-value="debouncedLoad" />
        </div>
      </v-expand-transition>
    </v-card>

    <v-card :loading="loading">
      <div style="overflow-x: auto">
      <v-table density="compact" hover>
        <thead>
          <tr>
            <th style="width:40px"></th>
            <th>ФИО</th>
            <th>Квалификация</th>
            <th>Статус</th>
            <th>Дата смены статуса</th>
            <th class="text-right">ЛП</th>
            <th class="text-right">ГП</th>
            <th class="text-right">НГП</th>
          </tr>
        </thead>
        <tbody>
          <template v-for="row in flatRows" :key="row._uid">
            <tr>
              <td>
                <v-btn v-if="row.hasChildren !== false" icon size="x-small" variant="text"
                  :loading="row._loadingChildren" @click="toggleExpand(row)">
                  <v-icon>{{ row._expanded ? 'mdi-chevron-down' : 'mdi-chevron-right' }}</v-icon>
                </v-btn>
              </td>
              <td :style="{ paddingLeft: (row._depth * 20 + 8) + 'px' }">{{ row.personName }}</td>
              <td>
                <v-chip v-if="row.qualification" size="x-small" color="secondary">{{ row.qualification.level }} [{{ row.qualification.title }}]</v-chip>
                <span v-else>—</span>
              </td>
              <td>
                <v-chip v-if="row.activityName" size="x-small" :color="activityColor(row.activityName)">{{ row.activityName }}</v-chip>
                <span v-else>—</span>
              </td>
              <td>{{ row.dateActivity || '—' }}</td>
              <td class="text-right">{{ fmt(row.personalVolume) }}</td>
              <td class="text-right">{{ fmt(row.groupVolume) }}</td>
              <td class="text-right">{{ fmt(row.groupVolumeCumulative) }}</td>
            </tr>
          </template>
          <tr v-if="!flatRows.length && !loading">
            <td colspan="8"><EmptyState /></td>
          </tr>
        </tbody>
      </v-table>
      </div>
      <div v-if="total > 25" class="d-flex justify-center pa-3">
        <v-pagination v-model="page" :length="Math.ceil(total / 25)" density="compact" @update:model-value="loadData" />
      </div>
    </v-card>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import api from '../api';
import { useDebounce } from '../composables/useDebounce';
import PageHeader from '../components/PageHeader.vue';
import EmptyState from '../components/EmptyState.vue';
import { fmt } from '../composables/useDesign';

const loading = ref(false);
const showAdvanced = ref(false);

const activeFilterCount = computed(() => {
  const f = filters.value;
  let c = 0;
  if (f.search) c++;
  if (f.qualification?.length) c++;
  if (f.levels?.length) c++;
  if (f.status?.length) c++;
  if (f.birth_date_from) c++;
  if (f.birth_date_to) c++;
  if (f.city) c++;
  if (f.lp_min) c++;
  if (f.lp_max) c++;
  if (f.gp_min) c++;
  if (f.gp_max) c++;
  if (f.ngp_min) c++;
  if (f.ngp_max) c++;
  if (f.termination_from) c++;
  if (f.termination_to) c++;
  return c;
});

function resetFilters() {
  filters.value = {
    search: '', qualification: [], levels: [], status: [],
    birth_date_from: '', birth_date_to: '',
    city: '',
    lp_min: '', lp_max: '', gp_min: '', gp_max: '', ngp_min: '', ngp_max: '',
    termination_from: '', termination_to: '',
  };
  loadData();
}
const items = ref([]);
const total = ref(0);
const page = ref(1);
const qualificationOptions = ref([]);
const statusOptions = [
  { title: 'Зарегистрирован', value: 'registered' },
  { title: 'Активен', value: 'active' },
  { title: 'Терминирован', value: 'terminated' },
  { title: 'Исключён', value: 'excluded' },
];
const filters = ref({
  search: '', qualification: [], levels: [], status: [],
  birth_date_from: '', birth_date_to: '',
  city: '',
  lp_min: '', lp_max: '', gp_min: '', gp_max: '', ngp_min: '', ngp_max: '',
  termination_from: '', termination_to: '',
});

let uidCounter = 0;
function enrichRows(rows, depth = 0) {
  return (rows || []).map(r => ({
    ...r,
    _uid: ++uidCounter,
    _depth: depth,
    _expanded: false,
    _loadingChildren: false,
    _children: [],
  }));
}

const flatRows = computed(() => {
  const result = [];
  function walk(rows) {
    for (const r of rows) {
      result.push(r);
      if (r._expanded && r._children.length) walk(r._children);
    }
  }
  walk(items.value);
  return result;
});

function activityColor(name) {
  if (!name) return 'grey';
  const l = name.toLowerCase();
  if (l.includes('актив')) return 'success';
  if (l.includes('терминир') || l.includes('исключ')) return 'error';
  if (l.includes('зарег')) return 'info';
  return 'warning';
}

async function toggleExpand(row) {
  if (row._expanded) {
    row._expanded = false;
    return;
  }
  if (row._children.length) {
    row._expanded = true;
    return;
  }
  row._loadingChildren = true;
  try {
    const { data } = await api.get(`/structure/${row.id}/children`);
    row._children = enrichRows(data.data || data, row._depth + 1);
    row._expanded = true;
  } catch {}
  row._loadingChildren = false;
}

const { debounced: debouncedLoad } = useDebounce(loadData, 400);

async function loadData() {
  loading.value = true;
  try {
    const params = { page: page.value };
    if (filters.value.search) params.search = filters.value.search;
    if (filters.value.qualification?.length) params.qualification = filters.value.qualification.join(',');
    if (filters.value.levels?.length) params.levels = filters.value.levels.join(',');
    if (filters.value.status?.length) params.status = filters.value.status.join(',');
    if (filters.value.birth_date_from) params.birth_date_from = filters.value.birth_date_from;
    if (filters.value.birth_date_to) params.birth_date_to = filters.value.birth_date_to;
    if (filters.value.city) params.city = filters.value.city;
    if (filters.value.lp_min) params.lp_min = filters.value.lp_min;
    if (filters.value.lp_max) params.lp_max = filters.value.lp_max;
    if (filters.value.gp_min) params.gp_min = filters.value.gp_min;
    if (filters.value.gp_max) params.gp_max = filters.value.gp_max;
    if (filters.value.ngp_min) params.ngp_min = filters.value.ngp_min;
    if (filters.value.ngp_max) params.ngp_max = filters.value.ngp_max;
    if (filters.value.termination_from) params.termination_from = filters.value.termination_from;
    if (filters.value.termination_to) params.termination_to = filters.value.termination_to;
    const { data } = await api.get('/structure', { params });
    uidCounter = 0;
    const responseData = data.data || data;
    items.value = enrichRows(responseData);
    total.value = data.total || responseData.length;
  } catch {}
  loading.value = false;
}

async function loadFilterOptions() {
  try {
    const [act, qual] = await Promise.all([
      api.get('/structure/activity-statuses'),
      api.get('/structure/qualification-levels'),
    ]);
    // activity-statuses can override statusOptions if backend provides them
    qualificationOptions.value = qual.data.map(q => ({ title: `${q.level} [${q.title}]`, value: q.id }));
  } catch {}
}

onMounted(() => {
  loadData();
  loadFilterOptions();
});
</script>
