// resources/js/pages/Admin/Reports.vue
<template>
  <div>
    <div class="d-flex align-center ga-2 mb-4">
      <v-icon size="32" color="primary">mdi-file-chart</v-icon>
      <h5 class="text-h5 font-weight-bold">Отчёты</h5>
    </div>

    <v-card class="pa-6">
      <div class="text-center">
        <v-icon size="64" color="grey-lighten-1" class="mb-4">mdi-hammer-wrench</v-icon>
        <div class="text-h6 text-medium-emphasis">Модуль отчётов — в разработке</div>
        <div class="text-body-2 text-medium-emphasis mt-2">Функционал будет доступен в ближайшем обновлении</div>
      </div>
    </v-card>
  </div>
</template>

// frontend/src/pages/Admin/Reports.tsx
import React from 'react';
import { Box, Card, CardContent, Typography } from '@mui/material';
import { Assessment } from '@mui/icons-material';

const Reports: React.FC = () => (
  <Box>
    <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
      <Assessment color="primary" />
      <Typography variant="h5" sx={{ fontWeight: 600 }}>Отчёты</Typography>
    </Box>
    <Card sx={{ maxWidth: 600 }}>
      <CardContent sx={{ textAlign: 'center', py: 6 }}>
        <Assessment sx={{ fontSize: 64, color: 'text.disabled', mb: 2 }} />
        <Typography variant="h6" color="text.secondary">
          Отчёты — в разработке
        </Typography>
        <Typography variant="body2" color="text.disabled" sx={{ mt: 1 }}>
          Функционал будет доступен в ближайшем обновлении
        </Typography>
      </CardContent>
    </Card>
  </Box>
);

export default Reports;
