// frontend/src/pages/Admin/Currencies.tsx
import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Card, CardContent, CircularProgress,
  Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper,
} from '@mui/material';
import { CurrencyExchange } from '@mui/icons-material';
import { adminApi } from '../../api/admin';

const Currencies: React.FC = () => {
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    adminApi.currencies()
      .then((res) => setData(res.data))
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 5 }}>
        <CircularProgress />
      </Box>
    );
  }

  const currencies = data?.currencies ?? data?.data ?? [];
  const vatRates = data?.vatRates ?? data?.vat ?? [];

  return (
    <Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
        <CurrencyExchange color="primary" />
        <Typography variant="h5" sx={{ fontWeight: 600 }}>Валюты и НДС</Typography>
      </Box>

      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Typography variant="h6" sx={{ mb: 2 }}>Валюты</Typography>
          <TableContainer component={Paper} variant="outlined">
            <Table size="small">
              <TableHead>
                <TableRow sx={{ bgcolor: '#f5f5f5' }}>
                  <TableCell>ID</TableCell>
                  <TableCell>Код</TableCell>
                  <TableCell>Название</TableCell>
                  <TableCell>Символ</TableCell>
                  <TableCell align="right">Курс</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {(Array.isArray(currencies) ? currencies : []).map((c: any, idx: number) => (
                  <TableRow key={c.id ?? idx} hover>
                    <TableCell>{c.id ?? '—'}</TableCell>
                    <TableCell>{c.code ?? '—'}</TableCell>
                    <TableCell>{c.name ?? '—'}</TableCell>
                    <TableCell>{c.symbol ?? '—'}</TableCell>
                    <TableCell align="right">
                      {c.rate?.toLocaleString('ru-RU', { minimumFractionDigits: 2 }) ?? '—'}
                    </TableCell>
                  </TableRow>
                ))}
                {(!Array.isArray(currencies) || currencies.length === 0) && (
                  <TableRow>
                    <TableCell colSpan={5} sx={{ textAlign: 'center', py: 3, color: 'text.secondary' }}>
                      Данные не найдены
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </TableContainer>
        </CardContent>
      </Card>

      <Card>
        <CardContent>
          <Typography variant="h6" sx={{ mb: 2 }}>Ставки НДС</Typography>
          <TableContainer component={Paper} variant="outlined">
            <Table size="small">
              <TableHead>
                <TableRow sx={{ bgcolor: '#f5f5f5' }}>
                  <TableCell>ID</TableCell>
                  <TableCell>Название</TableCell>
                  <TableCell align="right">Ставка (%)</TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {(Array.isArray(vatRates) ? vatRates : []).map((v: any, idx: number) => (
                  <TableRow key={v.id ?? idx} hover>
                    <TableCell>{v.id ?? '—'}</TableCell>
                    <TableCell>{v.name ?? '—'}</TableCell>
                    <TableCell align="right">{v.rate ?? v.percent ?? '—'}</TableCell>
                  </TableRow>
                ))}
                {(!Array.isArray(vatRates) || vatRates.length === 0) && (
                  <TableRow>
                    <TableCell colSpan={3} sx={{ textAlign: 'center', py: 3, color: 'text.secondary' }}>
                      Данные не найдены
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </TableContainer>
        </CardContent>
      </Card>
    </Box>
  );
};

export default Currencies;

// resources/js/pages/Admin/Currencies.vue
<template>
  <div>
    <div class="d-flex align-center ga-2 mb-4">
      <v-icon size="32" color="primary">mdi-currency-usd</v-icon>
      <h5 class="text-h5 font-weight-bold">Валюты и НДС</h5>
    </div>

    <v-row>
      <v-col cols="12" md="7">
        <v-card>
          <v-card-title class="text-subtitle-1 font-weight-bold">Курсы валют</v-card-title>
          <v-data-table :items="currencies" :headers="currencyHeaders" density="compact"
            hover no-data-text="Нет данных" :loading="loading">
            <template #item.rate="{ value }">{{ fmtRate(value) }}</template>
          </v-data-table>
        </v-card>
      </v-col>
      <v-col cols="12" md="5">
        <v-card>
          <v-card-title class="text-subtitle-1 font-weight-bold">Ставки НДС</v-card-title>
          <v-data-table :items="vatRates" :headers="vatHeaders" density="compact"
            hover no-data-text="Нет данных" :loading="loading">
            <template #item.rate="{ value }">{{ value }}%</template>
          </v-data-table>
        </v-card>
      </v-col>
    </v-row>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import api from '../../api';

const loading = ref(true);
const currencies = ref([]);
const vatRates = ref([]);

const currencyHeaders = [
  { title: 'Код', key: 'code', width: 80 },
  { title: 'Наименование', key: 'name' },
  { title: 'Символ', key: 'symbol', width: 80 },
  { title: 'Курс к RUB', key: 'rate', width: 140 },
  { title: 'Дата', key: 'updatedAt', width: 120 },
];

const vatHeaders = [
  { title: 'Наименование', key: 'name' },
  { title: 'Ставка', key: 'rate', width: 100 },
  { title: 'Действует с', key: 'effectiveFrom', width: 130 },
];

const fmtRate = (n) => Number(n || 0).toLocaleString('ru-RU', { minimumFractionDigits: 4 });

async function loadData() {
  loading.value = true;
  try {
    const { data } = await api.get('/admin/currencies');
    currencies.value = data.currencies || [];
    vatRates.value = data.vatRates || data.vat || [];
  } catch {}
  loading.value = false;
}

onMounted(loadData);
</script>
