// resources/js/pages/Products.vue
<template>
  <div>
    <PageHeader title="Перечень продуктов" icon="mdi-package-variant" />

    <!-- Condition 1: Tests not passed -->
    <v-alert v-if="accessChecked && !access.testsPassed" type="warning" variant="tonal" class="mb-4">
      <div class="font-weight-bold mb-1">Пройдите обучение</div>
      <div class="text-body-2">Для доступа к продуктам необходимо пройти обучение и сдать тесты.</div>
      <v-btn color="warning" variant="flat" size="small" to="/education" class="mt-2" prepend-icon="mdi-school">
        Перейти к обучению
      </v-btn>
    </v-alert>

    <template v-if="access.testsPassed">
      <!-- Filters -->
      <v-card class="mb-3 pa-3">
        <div class="d-flex ga-2 flex-wrap align-center">
          <v-text-field v-model="search" placeholder="Поиск по названию..."
            prepend-inner-icon="mdi-magnify" hide-details style="max-width:300px" @update:model-value="debouncedLoad" />
          <v-select v-model="category" :items="categoryOptions" label="Категория"
            clearable hide-details style="max-width:240px" @update:model-value="filterProducts" />
        </div>
      </v-card>

      <!-- Product cards -->
      <v-row>
        <v-col v-for="product in filteredProducts" :key="product.id" cols="12" sm="6" md="4" lg="3">
          <v-card class="pa-4 d-flex flex-column" height="100%">
            <!-- Image placeholder -->
            <v-img v-if="product.image" :src="product.image" height="140" cover class="rounded mb-3" />
            <div v-else class="bg-grey-lighten-3 rounded d-flex align-center justify-center mb-3" style="height:140px">
              <v-icon size="48" color="grey-lighten-1">mdi-image-outline</v-icon>
            </div>

            <div class="d-flex justify-space-between align-center mb-2">
              <v-chip size="x-small" :color="product.category?.color || 'grey'" variant="outlined">
                {{ product.category?.name || 'Без категории' }}
              </v-chip>
              <v-icon v-if="!product.available" color="grey" size="20">mdi-lock</v-icon>
              <v-icon v-else color="success" size="20">mdi-lock-open</v-icon>
            </div>

            <div class="text-subtitle-1 font-weight-bold mb-1">{{ product.name }}</div>
            <div class="text-body-2 text-medium-emphasis flex-grow-1 mb-3">{{ product.description }}</div>

            <div class="d-flex ga-2 flex-wrap">
              <v-btn variant="outlined" size="small" color="primary" to="/education" prepend-icon="mdi-school">
                Перейти к обучению
              </v-btn>
              <v-btn v-if="product.available" variant="flat" size="small" color="primary"
                prepend-icon="mdi-open-in-new" @click="openProduct(product)">
                Открыть продукт
              </v-btn>
              <v-btn v-else variant="flat" size="small" color="grey" disabled prepend-icon="mdi-lock">
                Открыть продукт
              </v-btn>
            </div>
          </v-card>
        </v-col>
      </v-row>

      <div v-if="!filteredProducts.length && !loading" class="text-center text-medium-emphasis pa-6">
        Продукты не найдены
      </div>
    </template>

    <!-- Condition 2: Requisites not verified -->
    <v-dialog v-model="reqDialog" max-width="420" persistent>
      <v-card>
        <v-card-title class="d-flex align-center ga-2">
          <v-icon color="warning">mdi-alert-circle</v-icon>
          Реквизиты не подтверждены
        </v-card-title>
        <v-card-text>
          Для доступа к данному продукту необходимо заполнить и подтвердить реквизиты в профиле.
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="reqDialog = false">Закрыть</v-btn>
          <v-btn color="primary" to="/profile" prepend-icon="mdi-account-cog">Перейти в профиль</v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <!-- Condition 3: Documents not accepted -->
    <v-dialog v-model="acceptDialog" max-width="420" persistent>
      <v-card>
        <v-card-title class="d-flex align-center ga-2">
          <v-icon color="warning">mdi-file-alert</v-icon>
          Документы не акцептованы
        </v-card-title>
        <v-card-text>
          Для доступа к данному продукту необходимо принять условия и акцептовать документы.
        </v-card-text>
        <v-card-actions>
          <v-spacer />
          <v-btn @click="acceptDialog = false">Закрыть</v-btn>
          <v-btn color="primary" @click="acceptDocuments" :loading="accepting" prepend-icon="mdi-check">
            Принять документы
          </v-btn>
        </v-card-actions>
      </v-card>
    </v-dialog>

    <v-overlay v-model="loading" class="align-center justify-center" persistent>
      <v-progress-circular indeterminate size="64" />
    </v-overlay>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import api from '../api';
import PageHeader from '../components/PageHeader.vue';

const loading = ref(true);
const products = ref([]);
const search = ref('');
const category = ref(null);
const categoryOptions = ref([]);
const access = ref({ testsPassed: false, requisitesVerified: false, documentsAccepted: false });
const accessChecked = ref(false);
const reqDialog = ref(false);
const acceptDialog = ref(false);
const accepting = ref(false);
const pendingProduct = ref(null);

const filteredProducts = computed(() => {
  let list = products.value;
  if (search.value) {
    const q = search.value.toLowerCase();
    list = list.filter(p => p.name?.toLowerCase().includes(q));
  }
  if (category.value) {
    list = list.filter(p => p.category?.id === category.value);
  }
  return list;
});

const { debounced: debouncedLoad } = useDebounce(loadData, 400);

function openProduct(product) {
  if (!access.value.requisitesVerified) {
    pendingProduct.value = product;
    reqDialog.value = true;
    return;
  }
  if (!access.value.documentsAccepted) {
    pendingProduct.value = product;
    acceptDialog.value = true;
    return;
  }
  if (product.url) {
    window.open(product.url, '_blank');
  }
}

async function acceptDocuments() {
  accepting.value = true;
  try {
    await api.post('/products/accept-documents');
    access.value.documentsAccepted = true;
    acceptDialog.value = false;
    if (pendingProduct.value?.url) {
      window.open(pendingProduct.value.url, '_blank');
    }
  } catch {}
  accepting.value = false;
}

async function loadProducts() {
  loading.value = true;
  try {
    const { data } = await api.get('/products');
    if (Array.isArray(data)) {
      products.value = data;
    } else {
      products.value = data.products || data.data || [];
      if (data.accessCheck) access.value = data.accessCheck;
      else if (data.access) access.value = data.access;
      if (data.categories) categoryOptions.value = data.categories.map(c => ({ title: c.name, value: c.id }));
    }
    accessChecked.value = true;
  } catch {}
  loading.value = false;
}

onMounted(loadProducts);
</script>

// frontend/src/pages/Products/index.tsx
import React, { useState, useEffect } from 'react';
import {
  Box, Typography, Card, CardContent, Grid, TextField, CircularProgress,
  Chip, Button, InputAdornment, FormControl, InputLabel, Select, MenuItem,
  Alert, Dialog, DialogTitle, DialogContent, DialogActions,
} from '@mui/material';
import {
  Search, Inventory, Lock, CheckCircle, School, Warning,
} from '@mui/icons-material';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import api from '../../api/client';
import { t } from '../../i18n';

interface ProductItem {
  id: number; name: string; description: string | null;
  typeName: string | null; accessible: boolean; testPassed: boolean;
}

interface AccessCheck {
  hasAccess: boolean; testsPassed: boolean;
  requisitesVerified: boolean; documentsAccepted: boolean;
  needsRequisites?: boolean; needsAcceptance?: boolean;
}

const Products: React.FC = () => {
  const [products, setProducts] = useState<ProductItem[]>([]);
  const [categories, setCategories] = useState<{ id: number; name: string }[]>([]);
  const [accessCheck, setAccessCheck] = useState<AccessCheck | null>(null);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [category, setCategory] = useState('');
  const [blockingDialog, setBlockingDialog] = useState<'requisites' | 'acceptance' | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    setLoading(true);
    const params: any = {};
    if (search) params.search = search;
    if (category) params.category = category;

    api.get('/products', { params })
      .then((res) => {
        setProducts(res.data.products);
        setCategories(res.data.categories || []);
        setAccessCheck(res.data.accessCheck);

        // Blocking dialogs
        const ac = res.data.accessCheck;
        if (ac?.needsRequisites) setBlockingDialog('requisites');
        else if (ac?.needsAcceptance) setBlockingDialog('acceptance');
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, [search, category]);

  if (loading) {
    return <Box sx={{ display: 'flex', justifyContent: 'center', py: 10 }}><CircularProgress /></Box>;
  }

  // No tests passed at all
  if (accessCheck && !accessCheck.testsPassed) {
    return (
      <Box>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
          <Inventory sx={{ fontSize: 32, color: 'primary.main' }} />
          <Typography variant="h5" sx={{ fontWeight: 600 }}>{t('nav.products')}</Typography>
        </Box>
        <Alert severity="info" icon={<School />} sx={{ mb: 3 }}>
          <Typography variant="body1" sx={{ fontWeight: 600 }}>
            Для доступа к продуктам необходимо пройти обучение
          </Typography>
          <Typography variant="body2" sx={{ mt: 1 }}>
            Пройдите хотя бы один тест в разделе «Обучение». После успешного прохождения теста
            будет открыт доступ к продукту, по которому сдан тест.
          </Typography>
          <Button variant="contained" sx={{ mt: 2 }} onClick={() => navigate('/education')}>
            Перейти к обучению
          </Button>
        </Alert>
      </Box>
    );
  }

  return (
    <Box>
      <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 3 }}>
        <Inventory sx={{ fontSize: 32, color: 'primary.main' }} />
        <Typography variant="h5" sx={{ fontWeight: 600 }}>{t('nav.products')}</Typography>
        <Chip label={`${products.length}`} color="primary" size="small" />
      </Box>

      {/* Access warnings */}
      {accessCheck && !accessCheck.requisitesVerified && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          Реквизиты не верифицированы. Заполните реквизиты ИП в разделе{' '}
          <Button size="small" onClick={() => navigate('/profile')}>Профиль → Реквизиты</Button>
        </Alert>
      )}
      {accessCheck && !accessCheck.documentsAccepted && accessCheck.requisitesVerified && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          Необходимо принять условия документов для доступа к продуктам.
        </Alert>
      )}

      {/* Filters */}
      <Card sx={{ mb: 3 }}>
        <CardContent sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', py: 2 }}>
          <TextField
            size="small" placeholder="Поиск по названию..." value={search}
            onChange={(e) => setSearch(e.target.value)}
            sx={{ minWidth: 250 }}
            slotProps={{ input: { startAdornment: <InputAdornment position="start"><Search /></InputAdornment> } }}
          />
          {categories.length > 0 && (
            <FormControl size="small" sx={{ minWidth: 200 }}>
              <InputLabel>Категория</InputLabel>
              <Select value={category} label="Категория"
                onChange={(e) => setCategory(e.target.value)}>
                <MenuItem value="">Все</MenuItem>
                {categories.map((c) => <MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}
              </Select>
            </FormControl>
          )}
        </CardContent>
      </Card>

      {/* Product cards */}
      <Grid container spacing={3}>
        {products.map((p, idx) => (
          <Grid size={{ xs: 12, sm: 6, md: 4 }} key={p.id}>
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.05 }}
            >
              <Card sx={{
                height: '100%', display: 'flex', flexDirection: 'column',
                opacity: p.accessible ? 1 : 0.6,
                border: p.accessible ? '1px solid #4CAF50' : '1px solid #e0e0e0',
              }}>
                <CardContent sx={{ flexGrow: 1, p: 3 }}>
                  <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
                    <Typography variant="h6" sx={{ fontWeight: 600 }}>{p.name}</Typography>
                    {p.accessible
                      ? <CheckCircle sx={{ color: 'success.main' }} />
                      : <Lock sx={{ color: 'text.disabled' }} />
                    }
                  </Box>

                  {p.typeName && (
                    <Chip label={p.typeName} size="small" variant="outlined" sx={{ mb: 1 }} />
                  )}

                  <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                    {p.description || 'Описание продукта будет добавлено позже.'}
                  </Typography>

                  {!p.testPassed && (
                    <Chip icon={<School />} label="Пройдите обучение" size="small" color="info" variant="outlined" />
                  )}
                </CardContent>

                <Box sx={{ p: 2, pt: 0, display: 'flex', gap: 1 }}>
                  <Button size="small" variant="outlined" onClick={() => navigate('/education')}>
                    Обучение
                  </Button>
                  {p.accessible && (
                    <Button size="small" variant="contained" color="success">
                      Открыть продукт
                    </Button>
                  )}
                </Box>
              </Card>
            </motion.div>
          </Grid>
        ))}
      </Grid>

      {products.length === 0 && (
        <Alert severity="info">Продукты не найдены</Alert>
      )}

      {/* Requisites blocking dialog */}
      <Dialog open={blockingDialog === 'requisites'} maxWidth="sm" fullWidth>
        <DialogTitle>Заполните реквизиты ИП</DialogTitle>
        <DialogContent>
          <Alert severity="info" sx={{ mt: 1 }}>
            Для доступа к продуктам необходимо заполнить реквизиты ИП и пройти верификацию.
          </Alert>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setBlockingDialog(null)}>Позже</Button>
          <Button variant="contained" onClick={() => { setBlockingDialog(null); navigate('/profile'); }}>
            Перейти к реквизитам
          </Button>
        </DialogActions>
      </Dialog>

      {/* Acceptance blocking dialog */}
      <Dialog open={blockingDialog === 'acceptance'} maxWidth="sm" fullWidth>
        <DialogTitle>Акцепт документов</DialogTitle>
        <DialogContent>
          <Alert severity="info" sx={{ mt: 1 }}>
            Для доступа к продуктам необходимо принять условия партнёрских документов.
          </Alert>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setBlockingDialog(null)}>Позже</Button>
          <Button variant="contained" onClick={() => { setBlockingDialog(null); navigate('/profile'); }}>
            Перейти в профиль
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
};

export default Products;
