// frontend/src/pages/Auth/Register.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, Link as RouterLink, useSearchParams } from 'react-router-dom';
import {
  Box, Card, CardContent, Typography, TextField, Button,
  Alert, InputAdornment, IconButton, CircularProgress, Grid,
  Stepper, Step, StepLabel, Checkbox, FormControlLabel, Divider,
} from '@mui/material';
import {
  Visibility, VisibilityOff, Email, Lock, Phone, Telegram,
  CalendarMonth, LocationCity, ArrowBack, CheckCircle,
} from '@mui/icons-material';
import { motion, AnimatePresence } from 'framer-motion';
import { useAuth } from '../../hooks/useAuth';
import { authApi, ReferralCheckResult } from '../../api/auth';
import AnimatedBackground from './AnimatedBackground';

const steps = ['Ввод данных', 'Проверка'];

const Register: React.FC = () => {
  const { register } = useAuth();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [step, setStep] = useState(0);
  const [form, setForm] = useState({
    firstName: '', lastName: '', patronymic: '',
    email: '', phone: '', telegram: '', birthDate: '', city: '',
    password: '', password_confirmation: '',
    consentPersonalData: false, consentTerms: false,
  });
  const [refCode] = useState(searchParams.get('ref') || '');
  const [mentor, setMentor] = useState<ReferralCheckResult['mentor'] | null>(null);
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [errors, setErrors] = useState<Record<string, string[]>>({});
  const [loading, setLoading] = useState(false);

  // Load mentor info from ref code
  useEffect(() => {
    if (refCode) {
      authApi.checkReferral(refCode).then((res) => {
        if (res.data.valid && res.data.mentor) {
          setMentor(res.data.mentor);
        }
      }).catch(() => {});
    }
  }, [refCode]);

  const update = (field: string) => (e: React.ChangeEvent<HTMLInputElement>) =>
    setForm({ ...form, [field]: e.target.value });

  const updateCheck = (field: string) => (e: React.ChangeEvent<HTMLInputElement>) =>
    setForm({ ...form, [field]: e.target.checked });

  const fieldError = (field: string) => errors[field]?.[0] || '';

  const activationDate = new Date();
  activationDate.setDate(activationDate.getDate() + 90);

  // Step 1 → Step 2: validate + check duplicates
  const handleNext = async () => {
    setError('');
    setErrors({});

    // Client-side validation
    const required = ['lastName', 'firstName', 'email', 'password', 'password_confirmation'];
    const missing = required.filter((f) => !(form as any)[f]);
    if (missing.length) {
      setError('Заполните все обязательные поля');
      return;
    }
    if (form.password !== form.password_confirmation) {
      setError('Пароли не совпадают');
      return;
    }
    if (form.password.length < 6) {
      setError('Пароль должен быть не менее 6 символов');
      return;
    }
    if (!form.consentPersonalData || !form.consentTerms) {
      setError('Необходимо дать согласие');
      return;
    }

    // Check duplicates
    setLoading(true);
    try {
      const res = await authApi.checkDuplicates({
        email: form.email,
        phone: form.phone || undefined,
        refCode: refCode || undefined,
      });
      if (res.data.duplicate) {
        setError(res.data.message || 'Обнаружен дубликат');
        setLoading(false);
        return;
      }
      setStep(1);
    } catch (err: any) {
      setError('Ошибка проверки данных');
    } finally {
      setLoading(false);
    }
  };

  // Step 2: submit registration
  const handleSubmit = async () => {
    setError('');
    setLoading(true);
    try {
      await register({
        ...form,
        refCode: refCode || undefined,
      });
      navigate('/');
    } catch (err: any) {
      if (err.response?.data?.errors) setErrors(err.response.data.errors);
      setError(err.response?.data?.message || 'Ошибка регистрации');
      setStep(0);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Box sx={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden', p: 2 }}>
      <AnimatedBackground />

      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        style={{ zIndex: 1, width: '100%', maxWidth: 580 }}
      >
        <Card sx={{ boxShadow: '0 20px 60px rgba(0,0,0,0.15)', backdropFilter: 'blur(20px)', bgcolor: 'rgba(255,255,255,0.95)' }}>
          <CardContent sx={{ p: { xs: 3, sm: 4 } }}>
            {/* Header */}
            <Box sx={{ textAlign: 'center', mb: 3 }}>
              <Typography variant="h3" sx={{ color: 'primary.main', fontWeight: 900, mb: 0.5 }}>DS</Typography>
              <Typography variant="body2" sx={{ color: 'text.secondary', letterSpacing: 4, textTransform: 'uppercase' }}>
                Consulting Platform
              </Typography>
            </Box>

            <Typography variant="h5" sx={{ mb: 2, textAlign: 'center', fontWeight: 600 }}>Регистрация</Typography>

            {/* Stepper */}
            <Stepper activeStep={step} sx={{ mb: 3 }}>
              {steps.map((label) => (
                <Step key={label}><StepLabel>{label}</StepLabel></Step>
              ))}
            </Stepper>

            {error && (
              <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
                <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>
              </motion.div>
            )}

            {mentor && (
              <Alert severity="info" icon={false} sx={{ mb: 2 }}>
                Наставник: <strong>{mentor.name}</strong> (код: {mentor.code})
              </Alert>
            )}

            <AnimatePresence mode="wait">
              {/* ===== STEP 1: Form ===== */}
              {step === 0 && (
                <motion.div key="step1" initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 20 }}>
                  <Grid container spacing={2}>
                    <Grid size={{ xs: 12, sm: 4 }}>
                      <TextField fullWidth label="Фамилия *" value={form.lastName} onChange={update('lastName')}
                        error={!!fieldError('lastName')} helperText={fieldError('lastName')} />
                    </Grid>
                    <Grid size={{ xs: 12, sm: 4 }}>
                      <TextField fullWidth label="Имя *" value={form.firstName} onChange={update('firstName')}
                        error={!!fieldError('firstName')} helperText={fieldError('firstName')} />
                    </Grid>
                    <Grid size={{ xs: 12, sm: 4 }}>
                      <TextField fullWidth label="Отчество" value={form.patronymic} onChange={update('patronymic')} />
                    </Grid>
                    <Grid size={12}>
                      <TextField fullWidth label="Email *" type="email" value={form.email} onChange={update('email')}
                        error={!!fieldError('email')} helperText={fieldError('email')}
                        slotProps={{ input: { startAdornment: <InputAdornment position="start"><Email color="action" /></InputAdornment> } }} />
                    </Grid>
                    <Grid size={{ xs: 12, sm: 6 }}>
                      <TextField fullWidth label="Телефон" value={form.phone} onChange={update('phone')}
                        slotProps={{ input: { startAdornment: <InputAdornment position="start"><Phone color="action" /></InputAdornment> } }} />
                    </Grid>
                    <Grid size={{ xs: 12, sm: 6 }}>
                      <TextField fullWidth label="Telegram" value={form.telegram} onChange={update('telegram')}
                        placeholder="@username"
                        slotProps={{ input: { startAdornment: <InputAdornment position="start"><Telegram color="action" /></InputAdornment> } }} />
                    </Grid>
                    <Grid size={{ xs: 12, sm: 6 }}>
                      <TextField fullWidth label="Дата рождения" type="date" value={form.birthDate}
                        onChange={update('birthDate')} slotProps={{ inputLabel: { shrink: true },
                        input: { startAdornment: <InputAdornment position="start"><CalendarMonth color="action" /></InputAdornment> } }} />
                    </Grid>
                    <Grid size={{ xs: 12, sm: 6 }}>
                      <TextField fullWidth label="Город" value={form.city} onChange={update('city')}
                        slotProps={{ input: { startAdornment: <InputAdornment position="start"><LocationCity color="action" /></InputAdornment> } }} />
                    </Grid>
                    <Grid size={12}>
                      <TextField fullWidth label="Пароль *" type={showPassword ? 'text' : 'password'}
                        value={form.password} onChange={update('password')}
                        error={!!fieldError('password')} helperText={fieldError('password')}
                        slotProps={{ input: {
                          startAdornment: <InputAdornment position="start"><Lock color="action" /></InputAdornment>,
                          endAdornment: <InputAdornment position="end">
                            <IconButton onClick={() => setShowPassword(!showPassword)} edge="end" size="small">
                              {showPassword ? <VisibilityOff /> : <Visibility />}
                            </IconButton>
                          </InputAdornment>,
                        } }} />
                    </Grid>
                    <Grid size={12}>
                      <TextField fullWidth label="Подтверждение пароля *" type="password"
                        value={form.password_confirmation} onChange={update('password_confirmation')}
                        slotProps={{ input: { startAdornment: <InputAdornment position="start"><Lock color="action" /></InputAdornment> } }} />
                    </Grid>
                    <Grid size={12}>
                      <FormControlLabel
                        control={<Checkbox checked={form.consentPersonalData} onChange={updateCheck('consentPersonalData')} color="primary" />}
                        label={<Typography variant="body2">Согласен на обработку персональных данных *</Typography>}
                      />
                      <FormControlLabel
                        control={<Checkbox checked={form.consentTerms} onChange={updateCheck('consentTerms')} color="primary" />}
                        label={<Typography variant="body2">Согласен с правилами использования платформы *</Typography>}
                      />
                    </Grid>
                  </Grid>

                  <motion.div whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                    <Button fullWidth variant="contained" size="large" onClick={handleNext} disabled={loading}
                      sx={{ py: 1.5, fontSize: 16, mt: 2, mb: 2, background: 'linear-gradient(135deg, #4CAF50 0%, #66BB6A 100%)', boxShadow: '0 4px 20px rgba(76,175,80,0.4)' }}>
                      {loading ? <CircularProgress size={24} color="inherit" /> : 'Далее →'}
                    </Button>
                  </motion.div>
                </motion.div>
              )}

              {/* ===== STEP 2: Review ===== */}
              {step === 1 && (
                <motion.div key="step2" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}>
                  <Alert severity="warning" sx={{ mb: 2 }}>
                    <strong>Проверьте данные.</strong> Исправить ФИО после завершения регистрации можно только через техподдержку.
                  </Alert>

                  {/* User data review */}
                  <Box sx={{ bgcolor: '#f9f9f9', borderRadius: 2, p: 2.5, mb: 2 }}>
                    <Grid container spacing={1.5}>
                      {[
                        { label: 'Фамилия', value: form.lastName },
                        { label: 'Имя', value: form.firstName },
                        { label: 'Отчество', value: form.patronymic || '—' },
                        { label: 'Email', value: form.email },
                        { label: 'Телефон', value: form.phone || '—' },
                        { label: 'Telegram', value: form.telegram || '—' },
                        { label: 'Дата рождения', value: form.birthDate || '—' },
                        { label: 'Город', value: form.city || '—' },
                      ].map((item) => (
                        <Grid size={{ xs: 6 }} key={item.label}>
                          <Typography variant="caption" color="text.secondary">{item.label}</Typography>
                          <Typography variant="body2" sx={{ fontWeight: 600 }}>{item.value}</Typography>
                        </Grid>
                      ))}
                    </Grid>
                  </Box>

                  {/* Mentor info */}
                  {mentor && (
                    <Box sx={{ bgcolor: '#f0f9f0', borderRadius: 2, p: 2.5, mb: 2, border: '1px solid', borderColor: 'primary.light' }}>
                      <Typography variant="subtitle2" sx={{ mb: 1, color: 'primary.main' }}>Информация о наставнике</Typography>
                      <Typography variant="body2"><strong>Наставник:</strong> {mentor.name}</Typography>
                      <Typography variant="body2"><strong>ID:</strong> {mentor.code}</Typography>
                      <Typography variant="body2">
                        <strong>Стартовый период:</strong> {new Date().toLocaleDateString('ru')} – {activationDate.toLocaleDateString('ru')}
                      </Typography>
                    </Box>
                  )}

                  {/* Activation info */}
                  <Box sx={{ bgcolor: '#fff8e1', borderRadius: 2, p: 2.5, mb: 3, border: '1px solid #ffe082' }}>
                    <Typography variant="subtitle2" sx={{ mb: 1, color: '#f57c00' }}>Стартовый период</Typography>
                    <Typography variant="body2" sx={{ mb: 1 }}>
                      <strong>Стартовый период</strong> — время, в течение которого ваш аккаунт должен быть активирован.
                      Для этого вам нужно сделать Личный объём не менее <strong>500 баллов</strong> суммарно за 90 дней с даты регистрации.
                    </Typography>
                    <Typography variant="body2">
                      Если объём <strong>500 баллов</strong> не будет выполнен — Соглашение о партнёрстве автоматически
                      аннулируется после даты окончания Стартового периода.
                    </Typography>
                  </Box>

                  <Box sx={{ display: 'flex', gap: 2 }}>
                    <Button variant="outlined" size="large" onClick={() => setStep(0)} startIcon={<ArrowBack />}
                      sx={{ flex: 1, py: 1.5 }}>
                      Назад
                    </Button>
                    <motion.div style={{ flex: 2 }} whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}>
                      <Button fullWidth variant="contained" size="large" onClick={handleSubmit} disabled={loading}
                        startIcon={loading ? undefined : <CheckCircle />}
                        sx={{ py: 1.5, fontSize: 16, background: 'linear-gradient(135deg, #4CAF50 0%, #66BB6A 100%)', boxShadow: '0 4px 20px rgba(76,175,80,0.4)' }}>
                        {loading ? <CircularProgress size={24} color="inherit" /> : 'Завершить регистрацию'}
                      </Button>
                    </motion.div>
                  </Box>
                </motion.div>
              )}
            </AnimatePresence>

            <Divider sx={{ my: 2 }} />
            <Typography variant="body2" sx={{ textAlign: 'center', color: 'text.secondary' }}>
              Уже есть аккаунт?{' '}
              <Typography component={RouterLink} to="/login" variant="body2"
                sx={{ color: 'primary.main', textDecoration: 'none', fontWeight: 600, '&:hover': { textDecoration: 'underline' } }}>
                Войти
              </Typography>
            </Typography>
          </CardContent>
        </Card>
      </motion.div>
    </Box>
  );
};

export default Register;

// resources/js/pages/Auth/Register.vue
<template>
  <div class="register-page" @mousemove="onMouseMove">
    <div class="bg-base"></div>
    <div class="parallax">
      <div class="blob blob-a" :style="layerStyle(0.02, 0.03)"></div>
      <div class="blob blob-b" :style="layerStyle(-0.035, 0.02)"></div>
      <div class="blob blob-c" :style="layerStyle(0.025, -0.03)"></div>
      <div class="blob blob-d" :style="layerStyle(-0.015, -0.02)"></div>
      <div class="blob blob-e" :style="layerStyle(0.04, 0.015)"></div>
      <div class="sphere" :style="layerStyle(0.012, 0.008)">
        <BrandWaves shape="circle" :width="420" :height="420"
          bg-color="#6EE87A" stroke-color="#ffffff"
          :rows="14" :columns="18" :amplitude="4" :frequency="1.0"
          :stroke-width="0.9" :stroke-opacity="0.55" />
      </div>
    </div>
    <div class="vignette"></div>
  <v-container class="fill-height position-relative" fluid style="z-index:2">
    <v-row justify="center" align="center">
      <v-col cols="12" sm="10" md="7" lg="5">
        <v-card class="pa-6 register-card" elevation="16" rounded="xl">
          <div class="text-center mb-4">
            <div class="text-h3 font-weight-black text-primary">DS</div>
            <div class="text-caption text-medium-emphasis" style="letter-spacing: 4px">КОНСАЛТИНГ ПЛАТФОРМА</div>
          </div>

          <div class="text-h5 text-center mb-4">Регистрация</div>

          <v-stepper v-model="step" flat>
            <v-stepper-header>
              <v-stepper-item :value="1" title="Ввод данных" />
              <v-divider />
              <v-stepper-item :value="2" title="Проверка" />
            </v-stepper-header>

            <v-stepper-window class="mt-4">
              <!-- Step 1 -->
              <v-stepper-window-item :value="1">
                <v-alert v-if="error" type="error" class="mb-3" density="compact">{{ error }}</v-alert>
                <v-row dense>
                  <v-col cols="12" sm="4"><v-text-field v-model="form.lastName" label="Фамилия *" /></v-col>
                  <v-col cols="12" sm="4"><v-text-field v-model="form.firstName" label="Имя *" /></v-col>
                  <v-col cols="12" sm="4"><v-text-field v-model="form.patronymic" label="Отчество" /></v-col>
                  <v-col cols="12"><v-text-field v-model="form.email" label="Электронная почта *" type="email" prepend-inner-icon="mdi-email" /></v-col>
                  <v-col cols="12" sm="6"><v-text-field v-model="form.phone" label="Телефон" prepend-inner-icon="mdi-phone" /></v-col>
                  <v-col cols="12" sm="6"><v-text-field v-model="form.telegram" label="Телеграм" prepend-inner-icon="mdi-send" placeholder="@username" /></v-col>
                  <v-col cols="12" sm="6"><v-text-field v-model="form.birthDate" label="Дата рождения" type="date" /></v-col>
                  <v-col cols="12" sm="6"><v-text-field v-model="form.city" label="Город" prepend-inner-icon="mdi-city" /></v-col>
                  <v-col cols="12"><v-text-field v-model="form.password" label="Пароль *" :type="showPw ? 'text' : 'password'" prepend-inner-icon="mdi-lock" :append-inner-icon="showPw ? 'mdi-eye-off' : 'mdi-eye'" @click:append-inner="showPw = !showPw" /></v-col>
                  <v-col cols="12"><v-text-field v-model="form.password_confirmation" label="Подтверждение пароля *" type="password" prepend-inner-icon="mdi-lock" /></v-col>
                  <v-col cols="12">
                    <v-checkbox v-model="form.consentPersonalData" label="Согласен на обработку персональных данных *" density="compact" />
                    <v-checkbox v-model="form.consentTerms" label="Согласен с правилами использования платформы *" density="compact" />
                  </v-col>
                </v-row>
                <v-btn block color="primary" size="large" @click="nextStep" :loading="loading">Далее →</v-btn>
              </v-stepper-window-item>

              <!-- Step 2 -->
              <v-stepper-window-item :value="2">
                <v-alert type="warning" class="mb-3" density="compact">
                  <strong>Проверьте данные.</strong> ФИО после регистрации можно изменить только через техподдержку.
                </v-alert>

                <v-card variant="tonal" class="mb-3 pa-3">
                  <v-row dense>
                    <v-col v-for="item in reviewItems" :key="item.label" cols="6">
                      <div class="text-caption text-medium-emphasis">{{ item.label }}</div>
                      <div class="text-body-2 font-weight-medium">{{ item.value || '—' }}</div>
                    </v-col>
                  </v-row>
                </v-card>

                <v-card color="amber-lighten-5" class="mb-4 pa-3" variant="flat">
                  <div class="text-subtitle-2 text-amber-darken-3 mb-1">Стартовый период</div>
                  <div class="text-body-2">
                    Для активации аккаунта необходимо набрать <strong>500 баллов</strong> личного объёма за 90 дней с даты регистрации.
                  </div>
                </v-card>

                <v-alert v-if="error" type="error" class="mb-3" density="compact">{{ error }}</v-alert>

                <div class="d-flex gap-3">
                  <v-btn variant="outlined" size="large" @click="step = 1" class="flex-grow-1">Назад</v-btn>
                  <v-btn color="primary" size="large" @click="handleRegister" :loading="loading" class="flex-grow-1">
                    Завершить регистрацию
                  </v-btn>
                </div>
              </v-stepper-window-item>
            </v-stepper-window>
          </v-stepper>

          <v-divider class="my-4" />
          <div class="text-center text-body-2">
            Уже есть аккаунт?
            <router-link to="/login" class="text-primary font-weight-bold text-decoration-none">Войти</router-link>
          </div>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
  </div>
</template>

<script setup>
import { ref, computed } from 'vue';
import { useRouter } from 'vue-router';
import { useAuthStore } from '../../stores/auth';
import api from '../../api';
import BrandWaves from '../../components/BrandWaves.vue';

const auth = useAuthStore();
const router = useRouter();
const step = ref(1);
const showPw = ref(false);
const error = ref('');
const loading = ref(false);
const form = ref({
  firstName: '', lastName: '', patronymic: '', email: '', phone: '',
  telegram: '', birthDate: '', city: '', password: '', password_confirmation: '',
  consentPersonalData: false, consentTerms: false,
});

// Parallax mouse tracking
const mx = ref(0);
const my = ref(0);
function onMouseMove(e) {
  const w = window.innerWidth;
  const h = window.innerHeight;
  mx.value = (e.clientX - w / 2) / (w / 2);
  my.value = (e.clientY - h / 2) / (h / 2);
}
function layerStyle(sx, sy) {
  return { transform: `translate3d(${mx.value * sx * 100}px, ${my.value * sy * 100}px, 0)` };
}

const reviewItems = computed(() => [
  { label: 'Фамилия', value: form.value.lastName },
  { label: 'Имя', value: form.value.firstName },
  { label: 'Отчество', value: form.value.patronymic },
  { label: 'Почта', value: form.value.email },
  { label: 'Телефон', value: form.value.phone },
  { label: 'Телеграм', value: form.value.telegram },
  { label: 'Дата рождения', value: form.value.birthDate },
  { label: 'Город', value: form.value.city },
]);

async function nextStep() {
  error.value = '';
  if (!form.value.lastName || !form.value.firstName || !form.value.email || !form.value.password) {
    error.value = 'Заполните все обязательные поля'; return;
  }
  if (form.value.password !== form.value.password_confirmation) {
    error.value = 'Пароли не совпадают'; return;
  }
  if (!form.value.consentPersonalData || !form.value.consentTerms) {
    error.value = 'Необходимо дать согласие'; return;
  }
  loading.value = true;
  try {
    const { data } = await api.post('/auth/check-duplicates', { email: form.value.email, phone: form.value.phone });
    if (data.duplicate) { error.value = data.message; return; }
    step.value = 2;
  } catch (e) {
    error.value = e.response?.data?.message || 'Ошибка проверки';
  } finally {
    loading.value = false;
  }
}

async function handleRegister() {
  error.value = '';
  loading.value = true;
  try {
    await auth.register(form.value);
    router.push('/');
  } catch (e) {
    error.value = e.response?.data?.message || 'Ошибка регистрации';
  } finally {
    loading.value = false;
  }
}
</script>

<style scoped>
.register-page {
  position: relative;
  min-height: 100vh;
  overflow: hidden;
  background: #0B1210;
}
.bg-base {
  position: fixed;
  inset: 0;
  z-index: 0;
  background:
    radial-gradient(1200px 800px at 15% 20%, rgba(110, 232, 122, 0.18), transparent 60%),
    radial-gradient(900px 700px at 85% 85%, rgba(46, 125, 50, 0.22), transparent 65%),
    linear-gradient(135deg, #0B1F14 0%, #0E2C1B 50%, #081510 100%);
  animation: bg-shift 24s ease-in-out infinite alternate;
}
.parallax {
  position: fixed;
  inset: -60px;
  z-index: 1;
  pointer-events: none;
}
.blob {
  position: absolute;
  border-radius: 50%;
  filter: blur(60px);
  opacity: 0.7;
  transition: transform 0.18s ease-out;
  will-change: transform, filter;
  animation: blob-drift 18s ease-in-out infinite alternate;
}
.blob-a { width: 520px; height: 520px; top: -60px; left: -80px;
  background: radial-gradient(circle, rgba(110, 232, 122, 0.75) 0%, transparent 70%);
  animation-duration: 16s; }
.blob-b { width: 440px; height: 440px; bottom: -100px; right: -80px;
  background: radial-gradient(circle, rgba(110, 232, 122, 0.55) 0%, transparent 70%);
  animation-duration: 22s; animation-delay: -4s; }
.blob-c { width: 340px; height: 340px; top: 40%; right: 10%;
  background: radial-gradient(circle, rgba(46, 125, 50, 0.55) 0%, transparent 70%);
  animation-duration: 19s; animation-delay: -8s; }
.blob-d { width: 260px; height: 260px; bottom: 15%; left: 10%;
  background: radial-gradient(circle, rgba(168, 244, 180, 0.45) 0%, transparent 70%);
  animation-duration: 24s; animation-delay: -2s; }
.blob-e { width: 380px; height: 380px; top: 15%; left: 55%;
  background: radial-gradient(circle, rgba(94, 220, 107, 0.35) 0%, transparent 70%);
  animation-duration: 20s; animation-delay: -10s; }

@keyframes blob-drift {
  0%   { filter: blur(60px) hue-rotate(0deg); opacity: 0.55; transform: scale(1) translate(0, 0); }
  50%  { filter: blur(72px) hue-rotate(18deg); opacity: 0.8; transform: scale(1.08) translate(14px, -10px); }
  100% { filter: blur(64px) hue-rotate(-14deg); opacity: 0.65; transform: scale(0.96) translate(-10px, 12px); }
}

@keyframes bg-shift {
  0%   { filter: hue-rotate(0deg) brightness(1); }
  50%  { filter: hue-rotate(12deg) brightness(1.05); }
  100% { filter: hue-rotate(-8deg) brightness(0.98); }
}
.sphere {
  position: absolute;
  right: -120px;
  bottom: -80px;
  width: 420px;
  height: 420px;
  opacity: 0.35;
  transition: transform 0.18s ease-out;
  will-change: transform;
}
.vignette {
  position: fixed;
  inset: 0;
  z-index: 1;
  pointer-events: none;
  background: radial-gradient(ellipse at center, transparent 50%, rgba(0, 0, 0, 0.45) 100%);
}
.register-card {
  backdrop-filter: blur(16px);
  background: rgba(var(--v-theme-surface), 0.95) !important;
  border: 1px solid rgba(var(--v-theme-brand), 0.3);
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.35);
}
@media (prefers-reduced-motion: reduce) {
  .blob, .sphere { transition: none !important; transform: none !important; animation: none !important; }
  .bg-base { animation: none !important; }
}
</style>
